(function(){
'use strict';
var BUILD='282';
function el(id){return document.getElementById(id)}
function setMode(mode){document.body.dataset.b28Mode=mode;localStorage.setItem('lz.beta28.mode',mode);document.querySelectorAll('[data-b28-mode]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.b28Mode===mode))});if(mode==='rider'){var b=document.querySelector('[data-b27-open="rider"]');if(b)b.click()}}
function modeBar(){var top=document.querySelector('#top');if(!top||el('b28-modebar'))return;var bar=document.createElement('nav');bar.id='b28-modebar';bar.className='b28-modebar';bar.setAttribute('aria-label','Workspace mode');bar.innerHTML='<button data-b28-mode="command" aria-pressed="true"><span>⌂</span>COMMAND</button><button data-b28-mode="guided"><span>＋</span>GUIDED LABEL</button><button data-b28-mode="rider"><span>➤</span>RIDER</button>';top.insertAdjacentElement('afterend',bar)}
function stepper(){var parcel=el('card-parcel');if(!parcel||el('b28-stepper'))return;var step=document.createElement('section');step.id='b28-stepper';step.className='b28-stepper';step.innerHTML='<div data-b28-step="1"><b>1</b><span>CUSTOMER<small>Select or create</small></span></div><i></i><div data-b28-step="2"><b>2</b><span>SCAN<small>Photo and contact</small></span></div><i></i><div data-b28-step="3"><b>3</b><span>PRICE<small>Sale and collect</small></span></div><i></i><div data-b28-step="4"><b>4</b><span>CONFIRM<small>Preview and print</small></span></div>';parcel.parentNode.insertBefore(step,parcel)}
function value(id){var n=el(id);return n&&String(n.value||'').trim()}
function amount(value){return Number(value||0).toLocaleString('fr-FR')+' Ar'}
function updateSteps(){var complete=0;if(value('rec-select'))complete=1;if((el('img-preview')&&el('img-preview').src)||value('ocr-text'))complete=2;if(Number(value('f-price')||value('price')||0)>0)complete=3;document.querySelectorAll('[data-b28-step]').forEach(function(n,i){n.classList.toggle('active',i===Math.min(complete,3));n.classList.toggle('done',i<complete)})}
function confirmationBar(){var actions=el('parcel-actions');if(!actions||el('b282-confirm'))return;var bar=document.createElement('section');bar.id='b282-confirm';bar.className='b282-confirm';bar.innerHTML='<div><small>READY TO CREATE</small><b id="b282-confirm-name">Choose a customer</b><span id="b282-confirm-total">Collect 0 Ar · Delivery 0 Ar</span></div><button type="button" id="b282-preview">PREVIEW</button>';actions.parentNode.insertBefore(bar,actions);var preview=el('card-preview');if(preview){preview.insertAdjacentHTML('afterbegin','<button type="button" class="b282-preview-close" id="b282-preview-close" aria-label="Close label preview">✕</button>');preview.classList.add('b282-sheet')}el('b282-preview').onclick=function(){if(preview){preview.classList.remove('mobile-collapsed');preview.classList.add('b282-open');if(typeof renderPreview==='function')renderPreview()}};el('b282-preview-close').onclick=function(){preview.classList.remove('b282-open');preview.classList.add('mobile-collapsed')}}
function updateConfirmation(){var rec=typeof currentRec==='function'?currentRec():null,name=el('b282-confirm-name'),total=el('b282-confirm-total');if(name)name.textContent=rec&&rec.name||'Choose a customer';if(total)total.textContent='Collect '+amount(value('f-cod'))+' · Delivery '+amount(value('f-ship')==='manual'?value('f-ship-manual'):value('f-ship'))}
function polish(){var pill=document.querySelector('.b2-beta-pill');if(pill)pill.textContent='BETA 2.8.2 · 282 · DECLUTTERED MOBILE';var over=document.querySelector('#card-home .ops-overline');if(over)over.textContent='OPERATIONS COMMAND · LIVE WORKSPACE';var title=document.querySelector('#card-home .ops-title');if(title)title.textContent='Every parcel under control.';document.documentElement.dataset.stitchBuild='approved-282';document.body.classList.add('b28-interface')}
function bind(){document.addEventListener('click',function(e){var b=e.target.closest('[data-b28-mode]');if(!b)return;setMode(b.dataset.b28Mode);if(typeof window.showMobileView==='function'&&window.matchMedia('(max-width:780px)').matches){if(b.dataset.b28Mode==='guided')window.showMobileView('new');if(b.dataset.b28Mode==='command')window.showMobileView('home')}});var old=window.showMobileView;if(typeof old==='function'&&!old.__b28){window.showMobileView=function(view){old.apply(this,arguments);if(view==='new')setMode('guided');else if(view==='home')setMode('command')};window.showMobileView.__b28=true;if(window.ACTIONS)ACTIONS.showMobileView=window.showMobileView}}
function init(){polish();modeBar();stepper();confirmationBar();bind();setMode(localStorage.getItem('lz.beta28.mode')||'command');updateSteps();updateConfirmation();setInterval(function(){updateSteps();updateConfirmation()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
