(function(){
'use strict';
var B2_VERSION='2.2.0-beta.1';
function el(id){return document.getElementById(id)}
function safe(s){return typeof esc==='function'?esc(s):String(s==null?'':s).replace(/[&<>"']/g,'')}
function rowById(id){return state.manifest.find(function(r){return r.id===id})}

function resolvedTheme(){var t=localStorage.getItem('lzb2.theme')||'system';if(t==='system')return matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';return t}
function applyTheme(){document.documentElement.dataset.theme=resolvedTheme();var b=el('b2-theme');if(b){var pref=localStorage.getItem('lzb2.theme')||'system';b.textContent=pref==='dark'?'☾':pref==='light'?'☀':'◐';b.title='Theme: '+pref}}
function cycleTheme(){var order=['system','light','dark'],now=localStorage.getItem('lzb2.theme')||'system',next=order[(order.indexOf(now)+1)%order.length];localStorage.setItem('lzb2.theme',next);applyTheme();toast('Theme: '+next,'ok')}

function installHeader(){
  var brand=document.querySelector('.brand h1');if(brand&&!document.querySelector('.b2-beta-pill'))brand.insertAdjacentHTML('afterend','<span class="b2-beta-pill">BETA 2.2 · 225</span>');
  var chips=document.querySelector('#top .chips');if(chips&&!el('b2-theme'))chips.insertAdjacentHTML('afterbegin','<button class="btn-ghost b2-theme" id="b2-theme" type="button" aria-label="Change light or dark theme">◐</button>');
  el('b2-theme').addEventListener('click',cycleTheme);applyTheme();
  var media=matchMedia('(prefers-color-scheme: dark)');if(media.addEventListener)media.addEventListener('change',function(){if((localStorage.getItem('lzb2.theme')||'system')==='system')applyTheme()});
}

function customerMatches(value){var q=String(value||'').trim().toLowerCase();if(!q)return[];return state.addr.filter(function(a){return [a.name,a.phone,a.area,a.address].some(function(v){return String(v||'').toLowerCase().indexOf(q)>=0})}).slice(0,5)}
function fillCustomer(prefix,id){var a=state.addr.find(function(x){return x.id===id});if(!a)return;[['name','name'],['phone','phone'],['area','area'],['addr','address'],['note','note']].forEach(function(m){var x=el(prefix+m[0]);if(x)x.value=a[m[1]]||''});document.querySelectorAll('.b2-suggest').forEach(function(x){x.classList.remove('open')});toast('Existing customer details completed','ok')}
function attachAutocomplete(inputId,prefix){var input=el(inputId);if(!input||input.dataset.b2Auto)return;input.dataset.b2Auto='1';var box=document.createElement('div');box.className='b2-suggest';input.insertAdjacentElement('afterend',box);input.addEventListener('input',function(){var list=customerMatches(input.value);box.innerHTML=list.map(function(a){return '<button type="button" data-b2-customer="'+safe(a.id)+'" data-b2-prefix="'+prefix+'"><b>'+safe(a.name)+'</b><small>'+safe([a.phone,a.area,a.address].filter(Boolean).join(' · '))+'</small></button>'}).join('');box.classList.toggle('open',!!list.length)});}
function saveModalAndCreateLabel(){var before=state.addr.length,editing=state.editingAddr;saveAddrModal();var selected=currentRec();if(!selected||(!editing&&state.addr.length===before))return;closeModal('m-addr');showMobileView('new');finishCustomerStep();var parcel=el('card-parcel');if(parcel&&!isMobileUI())parcel.scrollIntoView({behavior:'smooth',block:'start'});toast('Customer ready — complete and save the label','ok')}
function installCustomerCreateAction(){var save=document.querySelector('#m-addr [data-act="saveAddrModal"]');if(!save||el('b2-save-create'))return;save.insertAdjacentHTML('afterend','<button class="btn green" id="b2-save-create" type="button">SAVE &amp; CREATE LABEL</button>');el('b2-save-create').addEventListener('click',saveModalAndCreateLabel)}
document.addEventListener('click',function(e){var b=e.target.closest('[data-b2-customer]');if(b){fillCustomer(b.dataset.b2Prefix,b.dataset.b2Customer);return}if(!e.target.closest('.b2-suggest')&&!e.target.matches('#r-name,#am-name'))document.querySelectorAll('.b2-suggest').forEach(function(x){x.classList.remove('open')})});

function shareText(r){var rec=r.rec||{},sales=Number(r.price||r.cod||0),delivery=Number(r.ship||0),total=Number(r.cod||sales)+delivery;return [state.shop.name||'LabelOnZeWay','Order #'+(r.oid||r.id),rec.name,rec.phone,[rec.address,rec.area].filter(Boolean).join(', '),'Sales: '+money(sales),'Delivery: '+money(delivery),'Total to collect: '+money(total),r.deliverAt?('Delivery: '+r.deliverAt+(r.deliverTime?' '+r.deliverTime:'')):''].filter(Boolean).join('\n')}
function copyText(text,message){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text).then(function(){toast(message||'Label details copied','ok')});var area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');toast(message||'Label details copied','ok')}catch(e){toast('Select and copy the label details manually','err')}area.remove();return Promise.resolve()}
function normalizedWhatsAppPhone(phone){var digits=String(phone||'').replace(/\D/g,'');if(digits.indexOf('0')===0&&digits.length===10)digits='261'+digits.slice(1);return digits.length>=8?digits:''}
function openExternal(url){var a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove()}
function pdfAscii(value){return String(value==null?'':value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,' ').replace(/([\\()])/g,'\\$1')}
function labelPdfFile(r){var rec=r.rec||{},lines=[state.shop.name||'LabelOnZeWay','PICK '+(r.oid||r.id),'CUSTOMER: '+(rec.name||''),'PHONE: '+(rec.phone||''),'ADDRESS: '+[rec.address,rec.area].filter(Boolean).join(', '),'QUANTITY: '+(r.qty||1),'SALES: '+money(Number(r.price||0)),'COLLECT: '+money(Number(r.cod||0)),'DELIVERY: '+money(Number(r.ship||0)),'TOTAL: '+money(Number(r.cod||0)+Number(r.ship||0)),'DELIVERY DATE: '+(r.deliverAt||'')+' '+(r.deliverTime||''),'PAYMENT: '+(r.pay||'COD')];var content='BT\n/F1 15 Tf\n42 800 Td\n'+lines.map(function(x,i){return(i?'0 -27 Td\n':'')+'('+pdfAscii(x)+') Tj'}).join('\n')+'\nET';var objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>','<< /Length '+content.length+' >>\nstream\n'+content+'\nendstream'];var pdf='%PDF-1.4\n',offsets=[0];objects.forEach(function(obj,i){offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+obj+'\nendobj\n'});var xref=pdf.length;pdf+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n';offsets.slice(1).forEach(function(n){pdf+=String(n).padStart(10,'0')+' 00000 n \n'});pdf+='trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new File([new Blob([pdf],{type:'application/pdf'})],'Label-'+String(r.oid||r.id).replace(/[^\w-]/g,'-')+'.pdf',{type:'application/pdf'})}
function downloadFile(file){var url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1500)}
function createSecureLabelShare(r){var cloud=window.LabelOnZeWayCloud,token=cloud&&cloud.getAccessToken?cloud.getAccessToken():'';if(!token)return Promise.reject(new Error('Cloud sign-in required'));return fetch('sync-config.json',{cache:'no-store'}).then(function(x){return x.json()}).then(function(cfg){return fetch(String(cfg.supabaseUrl).replace(/\/$/,'')+'/functions/v1/create-label-share',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'apikey':cfg.supabaseAnonKey},body:JSON.stringify({profileId:PID,shop:state.shop,row:r})})}).then(function(resp){if(!resp.ok)return resp.text().then(function(t){throw new Error(t||('HTTP '+resp.status))});return resp.json()})}
function shareRow(id,channel){var r=rowById(id);if(!r)return;var file=labelPdfFile(r),title='Label '+(r.oid||''),phone=normalizedWhatsAppPhone(r.rec&&r.rec.phone),shareError=null;if(channel==='pdf'){downloadFile(file);toast('Latest label PDF downloaded','ok');return}toast('Preparing latest PDF and secure link…','ok');createSecureLabelShare(r).catch(function(error){shareError=error;return{trackingUrl:'',pdfUrl:''}}).then(function(shared){var link=shared.trackingUrl||shared.pdfUrl||'',text=shareText(r)+(link?'\nTrack / PDF: '+link:'');if(link){try{r.trackingToken=new URL(link).searchParams.get('token')||'';r.trackingUrl=shared.trackingUrl||'';persist()}catch(e){}}if(window.b24ShowShareResult)window.b24ShowShareResult(shared,file,shareError);if(channel==='whatsapp'){if(!link)downloadFile(file);openExternal('https://wa.me/'+(phone||'')+'?text='+encodeURIComponent(text));toast(link?'Secure link added to WhatsApp':'PDF downloaded — WhatsApp cannot attach it automatically from a web page','ok');return}if(channel==='messenger'){if(!link)downloadFile(file);copyText(text,'Label link/details copied — paste into Messenger');openExternal('https://www.messenger.com/');return}if(channel==='copy'){copyText(text);return}var payload={title:title,text:text,files:[file]};if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){return navigator.share(payload).catch(function(err){if(err&&err.name!=='AbortError'){downloadFile(file);copyText(text,'PDF downloaded and link copied')}})}if(navigator.share)return navigator.share({title:title,text:text});downloadFile(file);copyText(text,'PDF downloaded and link copied')})}

function moneyPanel(r){var sales=Number(r.price||r.cod||0),delivery=Number(r.ship||0),collect=Number(r.cod==null?sales:r.cod)+delivery;return '<div class="b2-money-summary"><span><small>SALES</small><b>'+money(sales)+'</b></span><span><small>DELIVERY</small><b>'+money(delivery)+'</b></span><span><small>TOTAL COD</small><b>'+money(collect)+'</b></span></div>'}
function enhanceManifest(){
  document.querySelectorAll('.mobile-manifest-item').forEach(function(item){var id=item.dataset.id,r=rowById(id),edit=item.querySelector('.mobile-manifest-edit');if(!r||!edit)return;
    var amount=item.querySelector('.mobile-amount');if(amount)amount.innerHTML=money(Number(r.cod||r.price||0)+Number(r.ship||0))+'<small>COD TOTAL · '+(r.done?'DELIVERED':'PENDING')+'</small>';
    if(!edit.querySelector('.b2-money-summary'))edit.insertAdjacentHTML('afterbegin',moneyPanel(r));
    var fields=edit.querySelectorAll('.mobile-field');fields.forEach(function(f){var lab=f.querySelector('label');if(lab&&lab.textContent.trim()==='ITEM / COLLECT'){lab.textContent='COLLECT (EXCL. DELIVERY)';f.insertAdjacentHTML('beforebegin','<div class="mobile-field"><label>SALES</label><input type="number" min="0" step="any" value="'+Number(r.price||0)+'" onchange="setMan(\''+id+'\',\'price\',this.value)"></div>')}});
    var acts=edit.querySelector('.mobile-manifest-actions');if(acts&&!edit.querySelector('.b2-share-actions'))acts.insertAdjacentHTML('afterend','<div class="b2-share-actions"><button class="btn blue" type="button" data-b2-share="native" data-id="'+safe(id)+'">↗ PDF + SECURE LINK</button><button class="btn green" type="button" data-b2-share="whatsapp" data-id="'+safe(id)+'">WHATSAPP CUSTOMER</button><button class="btn" type="button" data-b2-share="messenger" data-id="'+safe(id)+'">COPY + MESSENGER</button><button class="btn" type="button" data-b2-share="pdf" data-id="'+safe(id)+'">DOWNLOAD PDF</button><button class="btn" type="button" data-b2-share="copy" data-id="'+safe(id)+'">COPY LINK / TEXT</button></div><p class="b2-edit-note">The latest PDF is generated at sharing time. A secure expiring link requires Cloud sign-in and the deployed sharing backend.</p>');
  });
  document.querySelectorAll('.tbl-wrap tbody tr').forEach(function(tr,i){var r=state.manifest[i],acts=tr.querySelector('.mani-actions');if(!r)return;tr.setAttribute('data-manifest-id',r.id);if(!acts||acts.querySelector('[data-b2-share]'))return;acts.insertAdjacentHTML('afterbegin','<button class="mini-btn" title="Share latest PDF and secure link" data-b2-share="native" data-id="'+safe(r.id)+'">↗</button>')});
  var tt=el('totals');if(tt&&state.manifest.length){var open=state.manifest.filter(function(r){return !r.done}),sales=open.reduce(function(s,r){return s+Number(r.price||r.cod||0)},0),delivery=open.reduce(function(s,r){return s+Number(r.ship||0)},0),collect=open.reduce(function(s,r){return s+Number(r.cod==null?r.price:r.cod)+Number(r.ship||0)},0);tt.innerHTML='<div class="tot"><small>PARCELS</small><b>'+state.manifest.length+'</b></div><div class="tot hot"><small>SALES OPEN</small><b>'+money(sales)+'</b></div><div class="tot"><small>DELIVERY OPEN</small><b>'+money(delivery)+'</b></div><div class="tot grn"><small>TOTAL COD OPEN</small><b>'+money(collect)+'</b></div>'}
}
document.addEventListener('click',function(e){var b=e.target.closest('[data-b2-share]');if(b){e.preventDefault();shareRow(b.dataset.id,b.dataset.b2Share)}});

function deleteCurrentProfile(){var p=PROFILES.find(function(x){return x.id===PID});if(!p)return;if(PROFILES.length===1){toast('Create another profile before deleting this one','err');return}var fallbackId=el('b2-fallback-profile')&&el('b2-fallback-profile').value, fallback=PROFILES.find(function(x){return x.id===fallbackId&&x.id!==PID})||PROFILES.find(function(x){return x.id!==PID});if(!fallback){toast('Choose a fallback profile first','err');return}var typed=prompt('Type "'+p.name+'" to permanently delete this profile and switch to '+fallback.name+'.');if(typed!==p.name){if(typed!=null)toast('Profile name did not match','err');return}if(!confirm('Delete '+p.name+' and its Beta 2 customers, labels, manifest, archive and settings? The app will switch to '+fallback.name+'.'))return;Object.keys(localStorage).filter(function(k){return k.indexOf('b2.'+PID+'.')===0}).forEach(function(k){localStorage.removeItem(k)});PROFILES=PROFILES.filter(function(x){return x.id!==PID});localStorage.setItem('lzb2.profiles',JSON.stringify(PROFILES));localStorage.setItem('lzb2.profile',fallback.id);location.reload()}
function installProfileDelete(){var box=el('profile-create-box');if(!box||el('b2-delete-profile'))return;var fallbacks=PROFILES.filter(function(p){return p.id!==PID}).map(function(p){return '<option value="'+safe(p.id)+'">'+safe(p.name)+'</option>'}).join('');box.insertAdjacentHTML('beforeend','<div class="b2-profile-danger"><p>Delete the current company profile and switch safely to:</p><select id="b2-fallback-profile" aria-label="Fallback profile">'+(fallbacks||'<option value="">Create another profile first</option>')+'</select><button class="btn sm" id="b2-delete-profile" type="button" style="color:var(--red);border-color:var(--red)" '+(fallbacks?'':'disabled')+'>DELETE CURRENT PROFILE</button></div><div class="b2-role-grid"><div class="b2-role"><b>ADMIN</b><small>Profiles, staff membership, deletion, close-day and all operational changes.</small></div><div class="b2-role"><b>STAFF</b><small>Customers, labels, manifest, delivery and reconciliation; no profile or staff deletion.</small></div><div class="b2-role"><b>VIEWER</b><small>Read, search, export and print only. No business-record changes.</small></div></div>');el('b2-delete-profile').addEventListener('click',deleteCurrentProfile)}

function dailyPrefix(d){d=d||new Date();return ''+d.getDate()+(d.getMonth()+1)+String(d.getFullYear()).slice(-2)}
function dailySequence(prefix){var max=0,scan=function(r){var m=String(r&&r.oid||'').match(new RegExp('^'+prefix+'-(\\d+)$'));if(m)max=Math.max(max,Number(m[1])||0)};state.manifest.forEach(scan);state.archive.forEach(function(day){(day.rows||[]).forEach(scan)});state.labelVault.forEach(function(v){scan(v.row||v)});return max}
window.allocateOrderId=function(){var prefix=dailyPrefix(new Date()),cloud=window.LabelOnZeWayCloud,cloudId=cloud&&cloud.nextOrderIdentifier?cloud.nextOrderIdentifier(PID):null;if(cloudId){state.counter=(Number(state.counter)||0)+1;return prefix+'-'+cloudId}var key=K('dailySeq.'+prefix),stored=Number(load(key,0))||0,next=Math.max(stored,dailySequence(prefix))+1;save(key,next);state.counter=(Number(state.counter)||0)+1;return prefix+'-'+next};
function ensurePickNumbers(){var changed=false,groups={},rows=[];state.archive.forEach(function(day){(day.rows||[]).forEach(function(r){rows.push(r)})});state.manifest.forEach(function(r){rows.push(r)});rows.sort(function(a,b){return(Date.parse(a.addedAt)||0)-(Date.parse(b.addedAt)||0)}).forEach(function(r){var d=new Date(r.addedAt||r.deliverAt||Date.now());if(isNaN(d.getTime()))d=new Date();var prefix=dailyPrefix(d);groups[prefix]=groups[prefix]||{next:0,used:{}};var g=groups[prefix],m=String(r.oid||'').match(new RegExp('^'+prefix+'-(\\d+|OFF-[A-Z0-9-]+)$'));if(m&&!g.used[m[1]]){g.used[m[1]]=true;if(/^\\d+$/.test(m[1]))g.next=Math.max(g.next,Number(m[1])||0);return}do{g.next++}while(g.used[g.next]);r.oid=prefix+'-'+g.next;g.used[g.next]=true;changed=true});if(changed)persist()}

function exceptionEntries(){var out=[];state.manifest.forEach(function(r){if(r&&(!r.done||!r.paid))out.push({row:r,source:'ACTIVE'})});state.archive.forEach(function(day){(day.rows||[]).forEach(function(r){if(r&&(!r.done||!r.paid))out.push({row:r,source:'ARCHIVE'})})});return out.sort(function(a,b){return(Date.parse(a.row.addedAt)||0)-(Date.parse(b.row.addedAt)||0)})}
function updateExceptionCount(){var n=exceptionEntries().length,x=el('b2-exception-count'),b=el('b2-exception-btn');if(x)x.textContent=n;if(b){b.style.color=n?'var(--red)':'';b.style.borderColor=n?'var(--red)':''}return n}
function exceptionHTML(){var entries=exceptionEntries(),now=new Date(),unpaid=entries.filter(function(e){return !e.row.paid}).reduce(function(s,e){return s+Number(e.row.cod||0)+Number(e.row.ship||0)},0);return '<div class="a4sheet exception-report"><div class="a4head"><div><div class="a4shop">'+safe(state.shop.name)+'</div><div class="a4tag">DELIVERY &amp; PAYMENT CONTROL</div></div><div><div class="a4title">TWO-DAY EXCEPTION REPORT</div><div class="a4date">'+now.toLocaleString()+' · '+entries.length+' OPEN</div></div></div><div class="b2-exception-note">Automatically reviews the active manifest and archives every two days. An order remains here until both delivered and paid.</div><table class="a4tbl"><thead><tr><th>#</th><th>SOURCE</th><th>ORDER</th><th>CUSTOMER</th><th>PHONE</th><th>DELIVERY</th><th>PAYMENT</th><th>TOTAL</th><th>ISSUE</th></tr></thead><tbody>'+(entries.length?entries.map(function(e,i){var r=e.row,issue=[!r.done?'NOT DELIVERED':'',!r.paid?'NOT PAID':''].filter(Boolean).join(' + ');return '<tr><td>'+(i+1)+'</td><td>'+e.source+'</td><td><b>'+safe(r.oid||'—')+'</b></td><td>'+safe(r.rec&&r.rec.name||'—')+'</td><td>'+safe(r.rec&&r.rec.phone||'—')+'</td><td>'+safe(r.deliverAt||'—')+' '+safe(r.deliverTime||'')+'</td><td>'+safe(r.pay||'COD')+'</td><td class="money">'+money(Number(r.cod||0)+Number(r.ship||0))+'</td><td><b>'+issue+'</b></td></tr>'}).join(''):'<tr><td colspan="9" style="text-align:center;padding:8mm"><b>ALL CLEAR</b></td></tr>')+'</tbody></table><div class="a4totals"><div><small>EXCEPTIONS</small>'+entries.length+'</div><div><small>UNPAID TOTAL</small>'+money(unpaid)+'</div></div></div>'}
function openExceptionReport(){showPreview('TWO-DAY DELIVERY / PAYMENT CONTROL',exceptionHTML(),'b2exceptions',1,297)}
function maybeExceptionReport(){var d=new Date(),today=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate(),last=load(K('b2ExceptionLast'),'');updateExceptionCount();if(!last){save(K('b2ExceptionLast'),today);return}var a=new Date(today),b=new Date(last),days=Math.floor((a-b)/86400000);if(days>=2&&d.getHours()>=(Number(state.shop.reconHour)||9)){save(K('b2ExceptionLast'),today);setTimeout(function(){toast(updateExceptionCount()+' manifest exception(s) require follow-up',updateExceptionCount()?'err':'ok');openExceptionReport()},500)}}
function installExceptionAutomation(){var grid=document.querySelector('#manifest-action-menu .action-menu-grid');if(grid&&!el('b2-exception-btn')){var sales=[].slice.call(grid.children).find(function(x){return /SALES REPORT/i.test(x.textContent)});var html='<button class="btn sm" id="b2-exception-btn" type="button">⚠ 2-DAY REPORT <span id="b2-exception-count">0</span></button>';if(sales)sales.insertAdjacentHTML('afterend',html);else grid.insertAdjacentHTML('beforeend',html)}if(el('b2-exception-btn'))el('b2-exception-btn').addEventListener('click',openExceptionReport);var original=window.printPreviewNow;window.printPreviewNow=function(){if(previewMode==='b2exceptions'){closeModal('m-preview');doPrint('a4',exceptionHTML());toast('Opening exception report print dialog…','ok');return}return original()};if(window.ACTIONS)ACTIONS.printPreviewNow=window.printPreviewNow;maybeExceptionReport();setInterval(maybeExceptionReport,60000)}

function removeQwenUI(){var q=el('qwen-btn');if(q)q.remove();var label=[].slice.call(document.querySelectorAll('#m-settings p')).find(function(p){return /QWEN BACKEND/i.test(p.textContent)});if(label&&label.parentElement){var section=label.parentElement;section.style.display='none';section.setAttribute('aria-hidden','true')}}
var scanReviewImageKey='',scanReviewConfirmedKey='';
function scanImageKey(){var src=String(state.img||'');if(!src)return'';var file=state.currentFile;return [file&&file.name||'',file&&file.size||0,src.length,src.slice(-24)].join('|')}
function scanReviewCustomer(){var rec=currentRec();if(rec)return rec;var pending=state.pendingContact||{};return{name:pending.name||'',phone:pending.phone||'',area:pending.area||'',address:pending.address||''}}
function scanReviewDetected(){return state.b2DetectedContact||state.pendingContact||{}}
function updateScanReview(){var panel=el('b2-scan-review');if(!panel)return;var key=scanImageKey();if(key!==scanReviewImageKey){scanReviewImageKey=key;scanReviewConfirmedKey='';state.b2DetectedContact=null;panel.classList.remove('confirmed')}panel.classList.toggle('visible',!!key);if(!key)return;var rec=scanReviewCustomer(),detected=scanReviewDetected(),price=Number(val('f-price'))||0,ready=!!(currentRec()&&price>0),confirmed=scanReviewConfirmedKey===key;panel.classList.toggle('confirmed',confirmed);panel.classList.toggle('needs-attention',!ready);var stateEl=el('b2-scan-state');if(stateEl)stateEl.textContent=confirmed?'CONFIRMED':ready?'READY TO CONFIRM':'NEEDS INPUT';var customer=el('b2-scan-customer');if(customer)customer.textContent=rec.name||'Choose or save a customer';var contact=el('b2-scan-contact');if(contact)contact.textContent=[rec.phone,[rec.address,rec.area].filter(Boolean).join(', ')].filter(Boolean).join(' · ')||'No saved address/contact confirmed';var detectedBox=el('b2-scan-detected-line'),detectedAddress=el('b2-scan-detected-address'),detectedMeta=el('b2-scan-detected-meta'),hasDetected=!!(detected.address||detected.phone||detected.name);if(detectedBox)detectedBox.style.display=hasDetected?'':'none';if(detectedAddress)detectedAddress.textContent=detected.address||'Address not confidently detected';if(detectedMeta)detectedMeta.textContent=[detected.name,detected.phone].filter(Boolean).join(' · ');var priceText=el('b2-scan-price-summary');if(priceText)priceText.textContent=price>0?money(price):'Price required';var input=el('b2-scan-price-input');if(input&&document.activeElement!==input)input.value=price||'';var copy=el('b2-scan-confirmed-copy');if(copy)copy.textContent=(rec.name||'Customer')+' · '+(detected.address||rec.address||rec.area||'Address confirmed')+' · '+(price>0?money(price):'No price')+' · tap Edit to amend'}
function applyScanReviewPrice(){var input=el('b2-scan-price-input'),n=Number(input&&input.value)||0;if(n<=0){toast('Enter a valid price','err');if(input)input.focus();return}var price=el('f-price');if(price)price.value=n;var qty=Math.max(1,Number(el('f-qty')&&el('f-qty').value)||1),cod=el('f-cod');if(cod&&cod.value==='')cod.value=n*qty;scanReviewConfirmedKey='';queuePreview();updateScanReview();toast('Price applied · Collect = '+qty+' × unit price','ok')}
function confirmScanReview(){var price=Number(val('f-price'))||0,rec=currentRec();if(!rec){toast('Choose or save the customer first','err');editRecipientStep();updateScanReview();return}if(price<=0){toast('Enter and apply the price first','err');var input=el('b2-scan-price-input');if(input)input.focus();return}scanReviewConfirmedKey=scanImageKey();updateScanReview();toast('Scan details confirmed','ok')}
function editScanReview(){scanReviewConfirmedKey='';var panel=el('b2-scan-review');if(panel)panel.classList.remove('confirmed');updateScanReview()}
function installScanReview(){var drop=el('drop');if(!drop||el('b2-scan-review'))return;var wrap=document.createElement('div');wrap.className='b2-scan-workspace';drop.parentNode.insertBefore(wrap,drop);wrap.appendChild(drop);wrap.insertAdjacentHTML('beforeend','<aside class="b2-scan-review" id="b2-scan-review" aria-live="polite"><div class="b2-scan-head"><b>SCAN REVIEW</b><span class="b2-scan-state" id="b2-scan-state">NEEDS INPUT</span><button class="btn sm b2-scan-edit" id="b2-scan-edit" type="button">EDIT</button></div><div class="b2-scan-confirmed-copy" id="b2-scan-confirmed-copy"></div><div class="b2-scan-body"><div class="b2-scan-summary"><div class="b2-scan-line b2-detected-address" id="b2-scan-detected-line" style="display:none"><small>ADDRESS FOUND ON PICTURE</small><b id="b2-scan-detected-address">Address not detected</b><span id="b2-scan-detected-meta"></span></div><div class="b2-scan-line"><small>SELECTED CUSTOMER / SAVED ADDRESS</small><b id="b2-scan-customer">Choose customer</b><span id="b2-scan-contact"></span></div><div class="b2-scan-line"><small>PRICE DETECTED / ENTERED</small><b id="b2-scan-price-summary">Price required</b></div></div><div class="b2-scan-price"><input type="number" min="0" step="any" inputmode="decimal" id="b2-scan-price-input" placeholder="Manual price"><button class="btn" id="b2-scan-apply-price" type="button">APPLY</button></div><div class="b2-scan-actions"><button class="btn blue" id="b2-scan-run" type="button">SCAN PRICE + ADDRESS</button><button class="btn" id="b2-scan-customer-action" type="button">CUSTOMER</button><button class="btn green b2-scan-confirm" id="b2-scan-confirm" type="button">CONFIRM DETAILS</button></div></div></aside>');el('b2-scan-apply-price').addEventListener('click',applyScanReviewPrice);el('b2-scan-run').addEventListener('click',function(){scanPrice();updateScanReview()});el('b2-scan-customer-action').addEventListener('click',function(){editRecipientStep();updateScanReview()});el('b2-scan-confirm').addEventListener('click',confirmScanReview);el('b2-scan-edit').addEventListener('click',editScanReview);el('b2-scan-price-input').addEventListener('keydown',function(e){if(e.key==='Enter')applyScanReviewPrice()});['f-price','f-cod','rec-select'].forEach(function(id){var node=el(id);if(node)node.addEventListener('change',function(){scanReviewConfirmedKey='';updateScanReview()})});var originalMaybe=window.maybeSuggestContact;window.maybeSuggestContact=function(text){var detected=extractContact(text)||{};state.b2DetectedContact=detected;if(!currentRec()&&detected.phone){var digits=String(detected.phone).replace(/\D/g,''),match=state.addr.find(function(a){return String(a.phone||'').replace(/\D/g,'')===digits});if(match)rebuildRecSelect(match.id)}var result=originalMaybe(text);setTimeout(updateScanReview,0);return result};setInterval(updateScanReview,350);updateScanReview()}
function applyRolePermissions(){var cloud=window.LabelOnZeWayCloud,status=cloud&&cloud.getStatus?cloud.getStatus():null,role=status&&status.signedIn?status.role:'';document.body.dataset.workspaceRole=role||'local-admin';var deleteBtn=el('b2-delete-profile');if(deleteBtn)deleteBtn.style.display=role&&role!=='admin'?'none':'';var mutations=['addToManifest','savePrint','quickSaveRec','saveAddrModal','addProfile','addProfileFromSettings','deleteSelectedManifestLabels','clearManifest','closeDay','saveRecon','toggleDone','removeRow','delAddr','resetAll'];document.querySelectorAll('[data-act]').forEach(function(node){var blocked=role==='viewer'&&mutations.indexOf(node.getAttribute('data-act'))>=0;if(blocked&&!node.disabled){node.disabled=true;node.dataset.b2RoleDisabled='1'}else if(!blocked&&node.dataset.b2RoleDisabled==='1'){node.disabled=false;delete node.dataset.b2RoleDisabled}})}

var auditKey=function(){return K('audit.v22')};
function auditList(){return load(auditKey(),[])||[]}
function auditEvent(action,row,details){var cloud=window.LabelOnZeWayCloud,status=cloud&&cloud.getStatus?cloud.getStatus():{},entry={id:'au-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),at:new Date().toISOString(),action:action,pick:row&&row.oid||'',customer:row&&row.rec&&row.rec.name||'',details:String(details||''),role:status&&status.role||'local-admin',device:status&&status.deviceId||'local'};var list=auditList();list.unshift(entry);save(auditKey(),list.slice(0,1000));return entry}
function auditCsv(){var lines=[['Time','Action','Pick','Customer','Details','Role','Device']].concat(auditList().map(function(a){return[a.at,a.action,a.pick,a.customer,a.details,a.role,a.device]}));var csv=lines.map(function(row){return row.map(function(v){return'"'+String(v||'').replace(/"/g,'""')+'"'}).join(',')}).join('\r\n');downloadBlob(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),'LabelOnZeWay-Audit-'+new Date().toISOString().slice(0,10)+'.csv')}
function auditPanelHtml(){var rows=auditList();return '<div class="b22-audit-head"><div><b>OPERATIONAL AUDIT</b><small>Latest '+rows.length+' of 1,000 events retained on this profile</small></div><button class="btn sm" id="b22-audit-export">CSV</button><button class="btn sm" id="b22-audit-close">CLOSE</button></div><div class="b22-audit-list">'+(rows.length?rows.map(function(a){return'<div class="b22-audit-row"><b>'+safe(a.action)+'</b><span>'+safe(a.pick||'No Pick')+' · '+safe(a.customer||'—')+'</span><small>'+safe(new Date(a.at).toLocaleString())+' · '+safe(a.details)+'</small></div>'}).join(''):'<div class="empty">No recorded events yet.</div>')+'</div>'}
function openAuditPanel(){var panel=el('b22-audit-panel');if(!panel){panel=document.createElement('div');panel.id='b22-audit-panel';panel.className='b22-audit-panel';document.body.appendChild(panel)}panel.innerHTML=auditPanelHtml();panel.classList.add('open');el('b22-audit-close').onclick=function(){panel.classList.remove('open')};el('b22-audit-export').onclick=auditCsv}
function installAudit(){var grid=document.querySelector('#manifest-action-menu .action-menu-grid');if(grid&&!el('b22-audit-btn'))grid.insertAdjacentHTML('beforeend','<button class="btn sm" id="b22-audit-btn" type="button">☷ AUDIT</button>');if(el('b22-audit-btn'))el('b22-audit-btn').onclick=openAuditPanel;document.addEventListener('click',function(e){var b=e.target.closest('[data-act],[data-b2-share]');if(!b)return;var action=b.getAttribute('data-act')||('share-'+b.getAttribute('data-b2-share')),tracked=['addToManifest','savePrint','addSingleBatch','addAllBatch','printRow','printSelectedLabels','printAllBatchLabels','toggleDone','removeRow','deleteSelectedManifestLabels','closeDay','clearManifest','saveRecon'];if(tracked.indexOf(action)<0&&action.indexOf('share-')!==0)return;var id=b.getAttribute('data-arg')||b.getAttribute('data-id'),row=id?rowById(id):null;setTimeout(function(){auditEvent(action,row,id?'row action':'bulk action')},0)},true)}

var manifestQuery='',manifestStatus='all';
function manifestMatches(r){var q=manifestQuery.trim().toLowerCase(),hay=[r.oid,r.rec&&r.rec.name,r.rec&&r.rec.phone,r.rec&&r.rec.address,r.rec&&r.rec.area,r.pay,r.mmRef].join(' ').toLowerCase();if(q&&hay.indexOf(q)<0)return false;if(manifestStatus==='pending'&&r.done)return false;if(manifestStatus==='delivered'&&!r.done)return false;if(manifestStatus==='unpaid'&&r.paid)return false;if(manifestStatus==='paid'&&!r.paid)return false;if(manifestStatus==='override'&&!r.codManual)return false;if(manifestStatus==='missing'&&(r.rec&&r.rec.phone)&&(r.rec&&r.rec.address||r.rec&&r.rec.area))return false;return true}
function applyManifestFilters(){var shown=0;state.manifest.forEach(function(r){var visible=manifestMatches(r);if(visible)shown++;document.querySelectorAll('[data-manifest-id="'+CSS.escape(r.id)+'"],.mobile-manifest-item[data-id="'+CSS.escape(r.id)+'"]').forEach(function(node){node.style.display=visible?'':'none'})});var count=el('b22-filter-count');if(count)count.textContent=shown+' of '+state.manifest.length+' shown';var picks={},dupes=[];state.manifest.forEach(function(r){if(!r.oid)return;if(picks[r.oid])dupes.push(r.oid);picks[r.oid]=true});var warn=el('b22-pick-warning');if(warn){warn.textContent=dupes.length?'DUPLICATE PICK: '+Array.from(new Set(dupes)).join(', '):'';warn.style.display=dupes.length?'':'none'}}
function installManifestWorkspace(){var bar=el('mani-select-bar');if(!bar||el('b22-manifest-filter'))return;bar.insertAdjacentHTML('beforebegin','<div class="b22-manifest-filter" id="b22-manifest-filter"><input type="search" id="b22-manifest-search" placeholder="Search Pick, customer, phone, address, payment…"><select id="b22-manifest-status"><option value="all">All parcels</option><option value="pending">Pending</option><option value="delivered">Delivered</option><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="override">Manual overrides</option><option value="missing">Missing contact/address</option></select><span id="b22-filter-count"></span><b id="b22-pick-warning" style="display:none"></b></div>');el('b22-manifest-search').oninput=function(){manifestQuery=this.value;applyManifestFilters()};el('b22-manifest-status').onchange=function(){manifestStatus=this.value;applyManifestFilters()}}

function batchWorkflowState(it){if(it.status==='scanning'||it.status==='waiting')return'PROCESSING';if(!it.recId&&(!it.detectedContact||!(it.detectedContact.name||it.detectedContact.phone||it.detectedContact.address)))return'CONTACT REVIEW';if(it.price==null)return'PRICE REQUIRED';if(!it.recId)return'CUSTOMER REQUIRED';return'READY'}
function updateBatchOperationalCards(){state.batch.forEach(function(it){var row=el('brow-'+it.id);if(!row)return;var main=row.querySelector('.b-main'),box=row.querySelector('.b22-financial');if(!box&&main){box=document.createElement('div');box.className='b22-financial';main.insertBefore(box,main.firstChild)}if(box){var qty=Math.max(1,Number(it.qty)||1),unit=Number(it.price)||0,sales=qty*unit,collect=Number(it.cod==null?sales:it.cod),delivery=Number(it.ship)||0;box.innerHTML='<span class="b22-workflow '+batchWorkflowState(it).toLowerCase().replace(/\s+/g,'-')+'">'+batchWorkflowState(it)+'</span><span><small>SALES</small><b>'+money(sales)+'</b></span><span><small>DELIVERY</small><b>'+money(delivery)+'</b></span><span><small>TOTAL COD</small><b>'+money(collect+delivery)+'</b></span>'+(it.codManual?'<em>MANUAL COLLECT OVERRIDE</em>':'')}})}


var originalSetMan=window.setMan;window.setMan=function(id,k,v){var r=rowById(id),before=r?k==='name'||k==='phone'||k==='address'?String(r.rec&&r.rec[k]||''):String(r[k]==null?'':r[k]):'';if(k==='price'&&r){r.price=parseFloat(v)||0;if(!r.cod)r.cod=r.price*Math.max(1,Number(r.qty)||1);persist();renderStats();renderManifest()}else originalSetMan(id,k,v);if(r&&String(v)!==before)auditEvent('edit-'+k,r,before+' → '+v)};
var originalRenderManifest=window.renderManifest;window.renderManifest=function(){originalRenderManifest();enhanceManifest();applyManifestFilters()};
var originalQuickSave=window.quickSaveRec;window.quickSaveRec=function(){originalQuickSave();showMobileView('new');var p=el('card-parcel');if(p&&!isMobileUI())p.scrollIntoView({behavior:'smooth',block:'start'});toast('Customer ready — complete the label details','ok')};if(window.ACTIONS)ACTIONS.quickSaveRec=window.quickSaveRec;

function relabel(){document.title='LabelOnZeWay Beta 2.2';var desc=document.querySelector('meta[name="description"]');if(desc)desc.content='LabelOnZeWay Beta 2.2 operational labels, batch review, audit, manifest control and secure sharing.';var save=document.querySelector('[data-act="quickSaveRec"]');if(save)save.textContent='SAVE CUSTOMER & CREATE LABEL';var f=el('f-price');if(f){var lab=f.closest('.money-wrap')&&f.closest('.money-wrap').previousElementSibling;if(lab)lab.innerHTML='Unit price (<span id="cur-lbl-1">'+safe(state.shop.currency||'Ar')+'</span>)'}var cod=el('f-cod');if(cod){var l=cod.closest('div').querySelector('label.f');if(l)l.innerHTML='Sales collect (<span id="cur-lbl-2">'+safe(state.shop.currency||'Ar')+'</span>) — quantity × unit price'}var note=document.querySelector('#card-manifest .hint');if(note)note.textContent='search · filter · audit · edit · share · print'}
function boot(){ensurePickNumbers();installHeader();installProfileDelete();installCustomerCreateAction();installExceptionAutomation();installScanReview();installManifestWorkspace();installAudit();removeQwenUI();applyRolePermissions();setInterval(function(){applyRolePermissions();updateBatchOperationalCards()},500);attachAutocomplete('r-name','r-');attachAutocomplete('am-name','am-');relabel();renderManifest();renderOperationsDeck();updateBatchOperationalCards();console.info('LabelOnZeWay',B2_VERSION)}
boot();
})();
