(function(){
'use strict';
var VERSION='2.4.0-beta.1', selectedCustomers={};
function el(id){return document.getElementById(id)}
function clean(s){return String(s==null?'':s)}
function validPhone(text){var match=clean(text).match(/(?:\+?261[ .-]?)?(?:0)?(32|33|34|35|37|38|39)(?:[ .-]?\d){7}/);return match?match[0].trim():''}
function validAddress(text){var lines=clean(text).split(/\r?\n/).map(function(x){return x.trim()}).filter(Boolean);var keyword=/(?:^|\s)(?:lot|parcelle|cit[ée]|b\.?\s*p\.?|rue|akaik[yi]|ak[aà]iky|pr[eèé]s|acres?|en\s+face|[àa]\s+c[oô]t[ée]|arr[êe]t)(?:\s|[,:;.#-]|$)/i;return lines.find(function(line){return keyword.test(line)&&line.length>=6&&!/prix|price/i.test(line)})||''}
function strictExtract(text){var original=window.__b24OriginalExtract?window.__b24OriginalExtract(text):{},address=validAddress(text),phone=validPhone(text);return{name:original.name||'',phone:phone,address:address}}
function installOcrRules(){if(typeof window.extractContact!=='function')return;window.__b24OriginalExtract=window.extractContact;window.extractContact=strictExtract}
function statusOf(r){return r.trackingStatus||(r.done?'delivered':'ready_for_dispatch')}
function statusLabel(s){return({ready_for_dispatch:'READY',dispatched:'DISPATCHED',in_transit:'IN TRANSIT',delivered:'DELIVERED',exception:'EXCEPTION'})[s]||'READY'}
function updateTrackingBackend(r,status,note){if(!r.trackingToken)return Promise.resolve(false);var cloud=window.LabelOnZeWayCloud,token=cloud&&cloud.getAccessToken?cloud.getAccessToken():'';if(!token)return Promise.resolve(false);return fetch('sync-config.json',{cache:'no-store'}).then(function(x){return x.json()}).then(function(cfg){return fetch(String(cfg.supabaseUrl).replace(/\/$/,'')+'/functions/v1/create-label-share',{method:'PATCH',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'apikey':cfg.supabaseAnonKey},body:JSON.stringify({token:r.trackingToken,status:status,note:note||''})})}).then(function(resp){if(!resp.ok)throw new Error('Tracking update failed');return true})}
function editMilestone(id){var r=state.manifest.find(function(x){return x.id===id});if(!r)return;var answer=prompt('Update parcel milestone:\n\n1 Ready for dispatch\n2 Dispatched\n3 In transit\n4 Delivered\n5 Exception','3'),map={1:'ready_for_dispatch',2:'dispatched',3:'in_transit',4:'delivered',5:'exception'},status=map[answer];if(!status)return;var note=prompt('Optional public note','')||'';r.trackingStatus=status;r.statusUpdatedAt=new Date().toISOString();if(status==='delivered'){r.done=true;r.pod=true}persist();renderManifest();renderStats();updateTrackingBackend(r,status,note).then(function(sent){toast(sent?'Tracking platform updated':'Status saved locally; share the parcel to create its tracking link','ok')}).catch(function(err){toast(err.message,'err')})}
function installManifestStatus(){var old=window.renderManifest;if(typeof old!=='function'||old.__b24)return;window.renderManifest=function(){old.apply(this,arguments);document.querySelectorAll('[data-manifest-id],.mobile-manifest-item').forEach(function(node){var id=node.getAttribute('data-manifest-id')||node.dataset.id,r=state.manifest.find(function(x){return x.id===id});if(!r||node.querySelector('.b24-status'))return;var target=node.querySelector('.mani-actions,.mobile-amount')||node.querySelector('summary');if(target)target.insertAdjacentHTML('beforebegin','<button type="button" class="b24-status '+statusOf(r)+'" data-b24-status="'+id+'" title="Update tracking milestone">'+statusLabel(statusOf(r))+'</button>')})};window.renderManifest.__b24=true;document.addEventListener('click',function(e){var b=e.target.closest('[data-b24-status]');if(b)editMilestone(b.dataset.b24Status)});window.renderManifest()}
function installAddressBatch(){var box=el('am-list');if(!box)return;var search=el('am-search'),anchor=search&&search.parentNode;var tools=document.createElement('div');tools.className='b24-ab-tools';tools.innerHTML='<label class="chk"><input id="b24-ab-all" type="checkbox"> Select visible</label><button class="btn sm" id="b24-ab-delete" disabled>DELETE SELECTED (0)</button>';(anchor||box.parentNode).insertBefore(tools,box);function refresh(){var count=Object.keys(selectedCustomers).filter(function(k){return selectedCustomers[k]}).length,b=el('b24-ab-delete');b.disabled=!count;b.textContent='DELETE SELECTED ('+count+')';document.querySelectorAll('#am-list .ab-item').forEach(function(row){var id=row.dataset.b24id,check=row.querySelector('.b24-ab-check');if(check)check.checked=!!selectedCustomers[id];row.classList.toggle('b24-selected',!!selectedCustomers[id])})}var render=window.renderAmList;window.renderAmList=function(){render.apply(this,arguments);document.querySelectorAll('#am-list .ab-item').forEach(function(row){var edit=row.querySelector('[data-act="prepAddrModal"]'),id=edit&&edit.dataset.arg;if(!id)return;row.dataset.b24id=id;if(!row.querySelector('.b24-ab-check'))row.insertAdjacentHTML('afterbegin','<input type="checkbox" class="b24-ab-check" data-id="'+id+'" aria-label="Select customer">')});refresh()};box.addEventListener('change',function(e){if(!e.target.classList.contains('b24-ab-check'))return;selectedCustomers[e.target.dataset.id]=e.target.checked;refresh()});el('b24-ab-all').addEventListener('change',function(e){document.querySelectorAll('#am-list .b24-ab-check').forEach(function(c){selectedCustomers[c.dataset.id]=e.target.checked});refresh()});el('b24-ab-delete').addEventListener('click',function(){var ids=Object.keys(selectedCustomers).filter(function(k){return selectedCustomers[k]});if(!ids.length||!confirm('Delete '+ids.length+' selected address book entries?'))return;ids.forEach(function(id){if(window.LabelOnZeWayCloud&&LabelOnZeWayCloud.markEntityDeleted)LabelOnZeWayCloud.markEntityDeleted('customer',id,PID)});state.addr=state.addr.filter(function(a){return ids.indexOf(a.id)<0});selectedCustomers={};persist();rebuildRecSelect();renderAmList();renderBatch();toast(ids.length+' customers deleted','ok')});window.renderAmList()}
function sharePanel(){var p=el('b24-share-result');if(p)return p;p=document.createElement('aside');p.id='b24-share-result';p.className='b24-share-result';p.setAttribute('role','dialog');document.body.appendChild(p);return p}
window.b24ShowShareResult=function(result,file,error){var p=sharePanel(),link=result&&(result.trackingUrl||result.pdfUrl)||'';p.innerHTML='<h3>'+(link?'PDF + TRACKING LINK READY':'PDF READY LOCALLY')+'</h3><p class="'+(error?'b24-share-error':'')+'">'+(error?clean(error.message||error):'The latest label PDF has been prepared.')+'</p>'+(link?'<p>'+link+'</p>':'<p>Cloud link was not created. Sign in to Cloud and deploy the Beta 2.4 sharing backend; the local PDF is still available.</p>')+'<div class="b24-share-actions"><button class="btn green" id="b24-open-link" '+(link?'':'disabled')+'>OPEN TRACKING</button><button class="btn" id="b24-copy-link" '+(link?'':'disabled')+'>COPY LINK</button><button class="btn blue" id="b24-download-pdf">DOWNLOAD PDF</button><button class="btn" id="b24-close-share">CLOSE</button></div>';p.classList.add('open');el('b24-open-link').onclick=function(){window.open(link,'_blank','noopener')};el('b24-copy-link').onclick=function(){navigator.clipboard.writeText(link).then(function(){toast('Tracking link copied','ok')})};el('b24-download-pdf').onclick=function(){downloadFile(file)};el('b24-close-share').onclick=function(){p.classList.remove('open')}};
function installShareFeedback(){if(typeof window.createSecureLabelShare!=='function'||window.createSecureLabelShare.__b24)return;var original=window.createSecureLabelShare;window.createSecureLabelShare=function(r){return original(r).then(function(result){window.__b24LastShareResult=result;try{r.trackingToken=new URL(result.trackingUrl).searchParams.get('token')||'';r.trackingUrl=result.trackingUrl||'';persist()}catch(e){}return result}).catch(function(error){window.__b24LastShareError=error;throw error})};window.createSecureLabelShare.__b24=true;document.addEventListener('click',function(e){var b=e.target.closest('[data-b2-share]');if(!b)return;var r=state.manifest.find(function(x){return x.id===b.dataset.id});if(!r)return;var file=labelPdfFile(r);setTimeout(function(){b24ShowShareResult(window.__b24LastShareResult||null,file,window.__b24LastShareError||null);window.__b24LastShareResult=null;window.__b24LastShareError=null},1800)},true)}
function localMidnightGuard(){var now=new Date(),day=now.toISOString().slice(0,10),key='lz.b24.autoclose.'+PID,cloud=window.LabelOnZeWayCloud,status=cloud&&cloud.getStatus?cloud.getStatus():null;if(status&&status.signedIn)return;if(now.getHours()===23&&now.getMinutes()>=59&&localStorage.getItem(key)!==day&&state.manifest.length){state.manifest.forEach(function(r){r.trackingStatus='ready_for_dispatch';r.statusUpdatedAt=now.toISOString()});state.archive.unshift({id:uniqueId('d'),date:now.toISOString(),rows:state.manifest,autoClosed:true});state.manifest=[];localStorage.setItem(key,day);persist();renderManifest();renderStats();toast('23:59 manifest archived locally · email requires the configured cloud scheduler','ok')}}
function init(){installOcrRules();installManifestStatus();installAddressBatch();installShareFeedback();var pill=document.querySelector('.b2-beta-pill');if(pill)pill.textContent='BETA 2.4 · 241';setInterval(localMidnightGuard,20000);localMidnightGuard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
