(()=>{
  const $=(q,r=document)=>r.querySelector(q);
  let accessToken='';
  let adminUserId='';
  let config=null;

  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function status(text,type=''){const el=$('#v7-admin-status');if(!el)return;el.textContent=text||'';el.className='v7-admin-status'+(type?' '+type:'');}
  function cloudStatus(){try{return window.LabelOnZeWayCloud?.getStatus?.()||{};}catch(_e){return {};}}
  async function loadConfig(){if(config)return config;const r=await fetch('../labelonzeway/sync-config.json',{cache:'no-store'});if(!r.ok)throw new Error('Cloud configuration could not be loaded');config=await r.json();return config;}
  async function api(path,opts={}){
    const c=await loadConfig();
    if(!accessToken)throw new Error('Admin verification required');
    const r=await fetch(c.supabaseUrl.replace(/\/$/,'')+path,{...opts,headers:{apikey:c.supabaseAnonKey,Authorization:'Bearer '+accessToken,'Content-Type':'application/json',...(opts.headers||{})}});
    const text=await r.text();let body=null;try{body=text?JSON.parse(text):null;}catch(_e){body=text;}
    if(!r.ok)throw new Error(body?.message||body?.error_description||body?.hint||('HTTP '+r.status));
    return body;
  }
  function build(){if($('#v7-admin-users-overlay'))return;const wrap=document.createElement('div');wrap.id='v7-admin-users-overlay';wrap.className='v7-admin-users-overlay';wrap.innerHTML=`<section class="v7-admin-users" role="dialog" aria-modal="true" aria-labelledby="v7-admin-users-title"><div class="v7-admin-users-head"><div><h2 id="v7-admin-users-title">Supabase User Administration</h2><small id="v7-admin-workspace">Workspace</small></div><button class="v7-admin-close" type="button" aria-label="Close">×</button></div><div class="v7-admin-users-body"><div class="v7-admin-help">Add an existing <b>Supabase Auth user</b> to this workspace using their Auth User UUID. No service-role key is stored in the browser. Admin verification is required before membership changes.</div><div class="v7-admin-grid"><div class="v7-admin-field full"><label>Current admin password</label><input id="v7-admin-password" type="password" autocomplete="current-password" placeholder="Verify the signed-in admin account"></div><div class="v7-admin-field"><label>Supabase Auth User UUID</label><input id="v7-admin-user-id" type="text" inputmode="text" autocomplete="off" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"></div><div class="v7-admin-field"><label>Role</label><select id="v7-admin-role"><option value="staff">Staff</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select></div></div><div class="v7-admin-actions"><button class="v7-admin-btn" id="v7-admin-verify" type="button">Verify Admin</button><button class="v7-admin-btn primary" id="v7-admin-add" type="button">Add User</button><button class="v7-admin-btn" id="v7-admin-refresh" type="button">Refresh Users</button></div><div id="v7-admin-status" class="v7-admin-status"></div><div id="v7-admin-members" class="v7-admin-members"><div class="v7-admin-empty">Verify the admin account to load workspace users.</div></div></div></section>`;document.body.appendChild(wrap);
    $('.v7-admin-close',wrap).addEventListener('click',close);
    wrap.addEventListener('click',e=>{if(e.target===wrap)close();});
    $('#v7-admin-verify').addEventListener('click',verify);
    $('#v7-admin-add').addEventListener('click',addUser);
    $('#v7-admin-refresh').addEventListener('click',listUsers);
  }
  function open(){build();const cs=cloudStatus();$('#v7-admin-workspace').textContent=(cs.workspaceName||'Current workspace')+(cs.userEmail?' · '+cs.userEmail:'');$('#v7-admin-users-overlay').classList.add('open');document.body.classList.add('modal-open');if(!cs.signedIn||!cs.workspaceId)status('Sign in to Cloud and select a workspace first.','error');else status(accessToken?'Admin verified.':'Enter your current admin password, then Verify Admin.');}
  function close(){const el=$('#v7-admin-users-overlay');if(el)el.classList.remove('open');document.body.classList.remove('modal-open');const p=$('#v7-admin-password');if(p)p.value='';}
  async function verify(){try{const cs=cloudStatus();if(!cs.signedIn||!cs.workspaceId||!cs.userEmail)throw new Error('Cloud sign-in and workspace selection are required');const password=$('#v7-admin-password').value;if(!password)throw new Error('Enter the current admin password');status('Verifying admin account…');const c=await loadConfig();const r=await fetch(c.supabaseUrl.replace(/\/$/,'')+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:c.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email:cs.userEmail,password})});const data=await r.json();if(!r.ok||!data.access_token)throw new Error(data.error_description||data.msg||'Admin verification failed');accessToken=data.access_token;adminUserId=data.user?.id||'';$('#v7-admin-password').value='';const role=await api('/rest/v1/workspace_members?workspace_id=eq.'+encodeURIComponent(cs.workspaceId)+'&user_id=eq.'+encodeURIComponent(adminUserId)+'&select=role');if(!Array.isArray(role)||role[0]?.role!=='admin'){accessToken='';throw new Error('This account is not an admin of the selected workspace');}status('Admin verified.','ok');await listUsers();}catch(e){status(e.message||String(e),'error');}}
  async function listUsers(){try{const cs=cloudStatus();if(!accessToken)throw new Error('Verify Admin first');status('Loading users…');const rows=await api('/rest/v1/workspace_members?workspace_id=eq.'+encodeURIComponent(cs.workspaceId)+'&select=user_id,role,created_at&order=created_at.asc');render(rows||[]);status((rows||[]).length+' workspace user'+((rows||[]).length===1?'':'s')+' loaded.','ok');}catch(e){status(e.message||String(e),'error');}}
  function render(rows){const box=$('#v7-admin-members');if(!box)return;if(!rows.length){box.innerHTML='<div class="v7-admin-empty">No workspace users found.</div>';return;}box.innerHTML=rows.map(r=>`<div class="v7-admin-member" data-user="${esc(r.user_id)}"><div><code>${esc(r.user_id)}</code>${r.user_id===adminUserId?'<span class="v7-admin-self">YOU</span>':''}</div><select class="v7-admin-member-role" ${r.user_id===adminUserId?'disabled':''}><option value="admin" ${r.role==='admin'?'selected':''}>Admin</option><option value="staff" ${r.role==='staff'?'selected':''}>Staff</option><option value="viewer" ${r.role==='viewer'?'selected':''}>Viewer</option></select><button class="v7-admin-btn danger v7-admin-remove" type="button" ${r.user_id===adminUserId?'disabled':''}>Remove</button></div>`).join('');box.querySelectorAll('.v7-admin-member-role').forEach(sel=>sel.addEventListener('change',()=>changeRole(sel.closest('.v7-admin-member').dataset.user,sel.value)));box.querySelectorAll('.v7-admin-remove').forEach(btn=>btn.addEventListener('click',()=>removeUser(btn.closest('.v7-admin-member').dataset.user)));}
  async function addUser(){try{const cs=cloudStatus();if(!accessToken)throw new Error('Verify Admin first');const userId=$('#v7-admin-user-id').value.trim();const role=$('#v7-admin-role').value;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(userId))throw new Error('Enter a valid Supabase Auth User UUID');status('Adding user…');await api('/rest/v1/workspace_members',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({workspace_id:cs.workspaceId,user_id:userId,role})});$('#v7-admin-user-id').value='';status('User added to workspace.','ok');await listUsers();}catch(e){status(e.message||String(e),'error');}}
  async function changeRole(userId,role){try{if(userId===adminUserId)throw new Error('You cannot change your own admin role here');const cs=cloudStatus();status('Updating role…');await api('/rest/v1/workspace_members?workspace_id=eq.'+encodeURIComponent(cs.workspaceId)+'&user_id=eq.'+encodeURIComponent(userId),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role})});status('Role updated.','ok');}catch(e){status(e.message||String(e),'error');await listUsers().catch(()=>{});}}
  async function removeUser(userId){try{if(userId===adminUserId)throw new Error('You cannot remove your own admin membership here');if(!confirm('Remove this user from the current workspace?'))return;const cs=cloudStatus();status('Removing user…');await api('/rest/v1/workspace_members?workspace_id=eq.'+encodeURIComponent(cs.workspaceId)+'&user_id=eq.'+encodeURIComponent(userId),{method:'DELETE',headers:{Prefer:'return=minimal'}});status('User removed.','ok');await listUsers();}catch(e){status(e.message||String(e),'error');}}
  window.openAdminUsers=open;
})();
