(()=>{
'use strict';
const $=(q,r=document)=>r.querySelector(q);const LOCAL_AUDIT=/^(127\.0\.0\.1|localhost)$/.test(location.hostname)&&new URLSearchParams(location.search).get('audit')==='1';let gate=null,bootChecks=0,bootTimer=null,installed=false;
function cloudStatus(){try{return window.LabelOnZeWayCloud?.getStatus?.()||null}catch(_e){return null}}function signedIn(){return cloudStatus()?.signedIn===true}function setMessage(text,type=''){const el=$('#v7-auth-status');if(!el)return;el.textContent=text||'';el.className='v7-auth-status'+(type?' '+type:'')}
function ensureGate(){if(gate&&gate.isConnected)return gate;gate=document.createElement('div');gate.id='v7-auth-gate';gate.setAttribute('role','dialog');gate.setAttribute('aria-modal','true');gate.setAttribute('aria-label','LabelOnZeWay sign in');gate.innerHTML=`<form id="v7-auth-card" autocomplete="on"><div id="v7-auth-brand"><div class="mark">LZ</div><div><b>LabelOnZeWay</b><small>SHIP · TRACK · DELIVER</small></div></div><h1 id="v7-auth-title">Sign in to continue</h1><p id="v7-auth-note">Use your company user account. The same secure login is used on iPhone, Android and Mac.</p><label class="v7-auth-label" for="v7-auth-email">STAFF EMAIL</label><input id="v7-auth-email" type="email" autocomplete="username" inputmode="email" required><label class="v7-auth-label" for="v7-auth-password">PASSWORD</label><input id="v7-auth-password" type="password" autocomplete="current-password" required><button id="v7-auth-submit" type="submit">SIGN IN SECURELY</button><button id="v7-auth-forgot" type="button" class="secondary">FORGOT PASSWORD?</button><div id="v7-auth-status" class="v7-auth-status" aria-live="polite"></div><div id="v7-auth-meta">Secure company workspace</div></form>`;document.body.appendChild(gate);$('#v7-auth-card').addEventListener('submit',submit);$('#v7-auth-forgot').addEventListener('click',forgot);return gate}
function show(){ensureGate();if(signedIn())return hide();gate.classList.add('open');document.body.classList.add('v7-auth-locked')}function hide(){if(!gate)return;gate.classList.remove('open');document.body.classList.remove('v7-auth-locked');setMessage('');try{window.LabelOnZeWayV7ShowView?.('home')}catch(_e){}}
function installLogout(){if($('#v7-logout'))return;const host=$('.v7-tools')||$('#v7-shell');if(!host)return;const b=document.createElement('button');b.id='v7-logout';b.type='button';b.className='v7-logout';b.textContent='LOG OUT';b.setAttribute('aria-label','Log out of LabelOnZeWay');b.style.cssText='min-height:40px;border:1px solid rgba(255,142,73,.55);background:#25140d;color:#ffd7bf;border-radius:10px;padding:0 12px;font-weight:800;font-size:10px;letter-spacing:.04em;cursor:pointer';b.addEventListener('click',logout);host.appendChild(b)}
function logout(e){e?.preventDefault?.();const btn=$('#cloud-sign-out');if(!btn){alert('Cloud session is still starting. Please retry.');return}btn.click();setTimeout(()=>{try{window.LabelOnZeWayV7ShowView?.('home')}catch(_e){}show()},450)}
function copyIntoProduction(){const email=$('#v7-auth-email')?.value.trim()||'',password=$('#v7-auth-password')?.value||'',pe=$('#cloud-email'),pp=$('#cloud-password'),btn=$('#cloud-sign-in');if(!pe||!pp||!btn)return false;pe.value=email;pp.value=password;pe.dispatchEvent(new Event('input',{bubbles:true}));pp.dispatchEvent(new Event('input',{bubbles:true}));btn.click();return true}
function awaitResult(){let n=0;const timer=setInterval(()=>{n++;if(signedIn()){clearInterval(timer);$('#v7-auth-password').value='';hide();return}const msg=String($('#cloud-status')?.textContent||'').trim();if(/failed|invalid|incorrect|error/i.test(msg)){clearInterval(timer);setMessage(msg,'error');return}if(n>=24){clearInterval(timer);setMessage(msg||'Sign in is taking longer than expected. Check connection and retry.','error')}},500)}
function submit(e){e.preventDefault();const email=$('#v7-auth-email')?.value.trim()||'',password=$('#v7-auth-password')?.value||'';if(!email||!password){setMessage('Enter your staff email and password.','error');return}setMessage('Signing in securely…','busy');if(!copyIntoProduction()){setMessage('Secure cloud login is still starting. Please retry in a moment.','error');return}awaitResult()}
function forgot(){const email=$('#v7-auth-email')?.value.trim()||'',pe=$('#cloud-email'),btn=$('#cloud-forgot');if(!email){setMessage('Enter the staff email address first.','error');return}if(!pe||!btn){setMessage('Secure cloud login is still starting. Please retry in a moment.','error');return}pe.value=email;pe.dispatchEvent(new Event('input',{bubbles:true}));btn.click();setMessage('Password recovery request opened.','ok')}
function boot(){show();bootTimer=setInterval(()=>{bootChecks++;if(signedIn()){clearInterval(bootTimer);bootTimer=null;hide();return}if(window.LabelOnZeWayCloud?.getStatus||bootChecks>=30){clearInterval(bootTimer);bootTimer=null;show()}},500)}
function install(){if(installed||LOCAL_AUDIT)return;installed=true;ensureGate();installLogout();boot();document.addEventListener('click',e=>{if(e.target.closest?.('#cloud-sign-out'))setTimeout(show,500)},true);window.addEventListener('pageshow',()=>signedIn()?hide():show());window.addEventListener('online',()=>signedIn()?hide():show())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();