(()=>{
'use strict';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
function statusOfText(t){t=(t||'').toLowerCase();if(t.includes('delivered'))return'delivered';if(t.includes('in transit'))return'in_transit';if(t.includes('ready for dispatch'))return'pending';if(t.includes('exception'))return'exception';return'pending'}
function filterRows(filter,query){query=(query||'').trim().toLowerCase();const mobile=matchMedia('(max-width:900px)').matches;const rows=mobile?$$('#card-manifest .mobile-manifest-item'):$$('#card-manifest tbody tr');rows.forEach(r=>{const txt=(r.innerText||'').toLowerCase();const s=statusOfText(txt);const okFilter=filter==='all'||s===filter;const okQuery=!query||txt.includes(query);r.style.display=okFilter&&okQuery?'':'none'});}
function buildMobileTools(){if(!matchMedia('(max-width:900px)').matches)return;const card=$('#card-manifest');if(!card||$('#mf-mobile-tools'))return;const head=$('.card-head',card);const box=document.createElement('div');box.id='mf-mobile-tools';box.innerHTML='<input id="mf-mobile-search" type="search" placeholder="Search customer, phone, Pick ID…" autocomplete="off"><div id="mf-mobile-filters"><button class="active" data-filter="all">All</button><button data-filter="pending">Pending</button><button data-filter="in_transit">In Transit</button><button data-filter="delivered">Delivered</button></div><button id="mf-mobile-new" type="button">+ New Label</button>';if(head&&head.nextSibling)card.insertBefore(box,head.nextSibling);else card.prepend(box);let active='all';const search=$('#mf-mobile-search');search.addEventListener('input',()=>filterRows(active,search.value));$$('#mf-mobile-filters button').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.filter;$$('#mf-mobile-filters button').forEach(x=>x.classList.toggle('active',x===b));filterRows(active,search.value)}));$('#mf-mobile-new').addEventListener('click',()=>document.querySelector('[data-v7="label"]')?.click());}
function buildDesktopFilters(){if(!matchMedia('(min-width:901px)').matches)return;const card=$('#card-manifest');if(!card||$('#mf-desktop-filters'))return;const helper=$('#v7-manifest-print-helper');const bar=document.createElement('div');bar.id='mf-desktop-filters';bar.innerHTML='<button class="active" data-filter="all">All</button><button data-filter="pending">Pending</button><button data-filter="in_transit">In Transit</button><button data-filter="delivered">Delivered</button><button data-filter="exception">Exception</button>';if(helper&&helper.nextSibling)card.insertBefore(bar,helper.nextSibling);else{const head=$('.card-head',card);if(head&&head.nextSibling)card.insertBefore(bar,head.nextSibling)}$$('#mf-desktop-filters button').forEach(b=>b.addEventListener('click',()=>{$$('#mf-desktop-filters button').forEach(x=>x.classList.toggle('active',x===b));filterRows(b.dataset.filter,'')}));}
function relabelDesktop(){if(!matchMedia('(min-width:901px)').matches)return;const hs=$$('#card-manifest thead th');const labs=['','PICK ID','CUSTOMER / CONTACT','ADDRESS','PHONE','DATE / TIME','ITEMS (Ar)','DELIVERY (Ar)','COPIES','MM REF','PAYMENT','STATUS','ACTIONS'];hs.forEach((h,i)=>{if(labs[i]!==undefined)h.textContent=labs[i]});const t=$('#v7-manifest-toggle');if(t)t.textContent=document.body.classList.contains('v7-manifest-expanded')?'Compact':'Edit All Columns';}
function cleanMobile(){if(!matchMedia('(max-width:900px)').matches)return;const card=$('#card-manifest');if(!card)return;$$('.mobile-manifest-item>summary>.mani-check',card).forEach(c=>{c.removeAttribute('style')});}
function install(){buildMobileTools();buildDesktopFilters();relabelDesktop();cleanMobile();}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-v7="manifest"],#v7-manifest-toggle'))setTimeout(install,40)},true);
window.addEventListener('resize',()=>setTimeout(install,50),{passive:true});
const boot=()=>{install();let n=0;const t=setInterval(()=>{install();if(++n>24)clearInterval(t)},200)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
