(()=>{
  'use strict';
  const $=(q,r=document)=>r.querySelector(q);
  const DB='LabelOnZeWayPOD',STORE='files',BUCKET='labelonzeway-pod';
  let currentRow=null,podClient=null,podConfig=null;
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function st(text,type=''){const el=$('#v7-pod-status');if(!el)return;el.textContent=text||'';el.className='v7-pod-status'+(type?' '+type:'');}
  function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
  async function putFile(key,file){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,key);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)}})}
  async function getFile(key){if(!key)return null;const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>{d.close();resolve(req.result||null)};req.onerror=()=>{d.close();reject(req.error)}})}
  function selected(){try{return typeof window.selectedManifestRows==='function'?window.selectedManifestRows():[];}catch(_e){return []}}
  function pickLabel(r){return String(r?.pickId||r?.pick||r?.oid||r?.id||'Parcel')}
  function safePart(value,fallback='item'){const s=String(value||fallback).trim().replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);return s||fallback}
  async function cloud(){const status=window.LabelOnZeWayCloud?.getStatus?.();if(!status?.signedIn||!status.workspaceId||!window.supabase?.createClient)return null;if(!podConfig)podConfig=await fetch('../labelonzeway/sync-config.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Cloud configuration unavailable');return r.json()});if(!podClient)podClient=window.supabase.createClient(podConfig.supabaseUrl,podConfig.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:false,detectSessionInUrl:false}});const session=(await podClient.auth.getSession()).data?.session;if(!session)return null;return {client:podClient,status}}
  async function uploadCloud(file,row){const ctx=await cloud();if(!ctx)return null;const path=[ctx.status.workspaceId,safePart(ctx.status.profileSyncId||ctx.status.profileId||'profile','profile'),safePart(row?.id||row?.oid||pickLabel(row),'parcel'),Date.now()+'-'+safePart(file.name||'pod')].join('/');const result=await ctx.client.storage.from(BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(result.error)throw result.error;return result.data?.path||path}
  async function signedCloudUrl(path){const ctx=await cloud();if(!ctx)throw new Error('Sign in to Cloud to open this POD on another device');const result=await ctx.client.storage.from(BUCKET).createSignedUrl(path,300);if(result.error)throw result.error;return result.data?.signedUrl||''}
  function build(){if($('#v7-pod-overlay'))return;const el=document.createElement('div');el.id='v7-pod-overlay';el.className='v7-pod-overlay';el.innerHTML=`<section class="v7-pod-card" role="dialog" aria-modal="true"><div class="v7-pod-head"><div><h2>Proof of Delivery</h2><small id="v7-pod-parcel">Selected parcel</small></div><button type="button" class="v7-pod-close" aria-label="Close">×</button></div><div class="v7-pod-body"><div id="v7-pod-existing" class="v7-pod-summary" style="display:none"></div><div class="v7-pod-grid"><div class="v7-pod-field"><label>Recipient name</label><input id="v7-pod-recipient" autocomplete="name" placeholder="Person who received the parcel"></div><div class="v7-pod-field"><label>Electronic acknowledgement</label><input id="v7-pod-signature" autocomplete="off" placeholder="Type recipient name / initials"></div><div class="v7-pod-field full"><label>POD upload</label><div class="v7-pod-file"><input id="v7-pod-file" type="file" accept="image/*,application/pdf" capture="environment"><small>Photo or PDF, max 12 MB. Signed-in users keep a private cloud copy for cross-device access.</small></div></div><div class="v7-pod-field full"><label>Delivery note</label><textarea id="v7-pod-note" placeholder="Optional delivery note"></textarea></div></div><div class="v7-pod-actions"><button type="button" class="v7-pod-btn primary" id="v7-pod-save">Save POD + Mark Delivered</button><button type="button" class="v7-pod-btn secondary" id="v7-pod-view">View Existing POD</button><button type="button" class="v7-pod-btn" id="v7-pod-save-only">Save POD Only</button></div><div id="v7-pod-status" class="v7-pod-status"></div></div></section>`;document.body.appendChild(el);$('.v7-pod-close',el).addEventListener('click',close);el.addEventListener('click',e=>{if(e.target===el)close()});$('#v7-pod-save').addEventListener('click',()=>save(true));$('#v7-pod-save-only').addEventListener('click',()=>save(false));$('#v7-pod-view').addEventListener('click',viewExisting)}
  function open(){const rows=selected();if(rows.length!==1){try{window.toast?.('Select exactly one parcel before adding POD','err')}catch(_e){};return}currentRow=rows[0];build();$('#v7-pod-parcel').textContent='Parcel '+pickLabel(currentRow);$('#v7-pod-recipient').value=currentRow.podRecipient||'';$('#v7-pod-signature').value=currentRow.podSignature||'';$('#v7-pod-note').value=currentRow.podNote||'';$('#v7-pod-file').value='';const ex=$('#v7-pod-existing');if(currentRow.podAvailable){ex.style.display='block';ex.innerHTML='<b>POD already recorded</b><br>'+esc(currentRow.podFileName||'Proof file')+' · '+esc(currentRow.podUpdatedAt?new Date(currentRow.podUpdatedAt).toLocaleString():'')+(currentRow.podCloudPath?'<br>☁ Private cloud copy available':'<br>Local device copy');}else ex.style.display='none';st('');$('#v7-pod-overlay').classList.add('open');document.body.classList.add('modal-open')}
  function close(){$('#v7-pod-overlay')?.classList.remove('open');document.body.classList.remove('modal-open');currentRow=null}
  async function save(markDelivered){try{if(!currentRow)throw new Error('No parcel selected');const recipient=$('#v7-pod-recipient').value.trim(),signature=$('#v7-pod-signature').value.trim(),note=$('#v7-pod-note').value.trim(),file=$('#v7-pod-file').files?.[0]||null;if(!recipient)throw new Error('Recipient name is required');if(!signature)throw new Error('Electronic acknowledgement is required');if(!file&&!currentRow.podAvailable)throw new Error('Upload a POD photo or PDF first');if(file&&file.size>12*1024*1024)throw new Error('POD file is larger than 12 MB');st('Saving POD…','busy');const now=new Date().toISOString(),key='pod-'+String(currentRow.id||currentRow.oid||Date.now());let cloudPath=currentRow.podCloudPath||'',cloudError='';if(file){await putFile(key,file);try{cloudPath=await uploadCloud(file,currentRow)||''}catch(e){cloudError=String(e?.message||e)}}currentRow.podAvailable=true;currentRow.podRecipient=recipient;currentRow.podSignature=signature;currentRow.podNote=note;currentRow.podUpdatedAt=now;currentRow.podStorageKey=key;currentRow.podFileName=file?.name||currentRow.podFileName||'POD';currentRow.podMime=file?.type||currentRow.podMime||'';currentRow.podSource=cloudPath?'private-cloud+local':'local-upload';currentRow.podCloudPath=cloudPath;if(markDelivered){if(typeof window.setDeliveryStatus==='function')window.setDeliveryStatus(currentRow.id,'delivered');else{currentRow.deliveryStatus='delivered';currentRow.done=true;currentRow.statusUpdatedAt=now;try{window.appendMilestone?.(currentRow,'delivered',now,'POD captured','pod')}catch(_e){}}}try{window.persist?.()}catch(_e){};try{window.renderManifest?.()}catch(_e){};try{window.renderStats?.()}catch(_e){};try{await window.LabelOnZeWayCloud?.captureNow?.(window.PID,false)}catch(_e){};try{await window.syncTrackingGateway?.(false)}catch(_e){};if(cloudError)st('POD saved locally. Cloud copy failed: '+cloudError,'error');else st(markDelivered?(cloudPath?'POD saved to private cloud + local cache. Parcel marked Delivered.':'POD saved locally. Parcel marked Delivered.'):(cloudPath?'POD saved to private cloud + local cache.':'POD saved locally.'),'ok');if(!cloudError)setTimeout(close,1100)}catch(e){st(e.message||String(e),'error')}}
  async function viewExisting(){try{if(!currentRow)throw new Error('No parcel selected');let file=null;if(currentRow.podStorageKey){try{file=await getFile(currentRow.podStorageKey)}catch(_e){}}if(file){const url=URL.createObjectURL(file);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000);return}if(currentRow.podCloudPath){st('Opening private cloud POD…','busy');const url=await signedCloudUrl(currentRow.podCloudPath);if(!url)throw new Error('Could not create a secure POD link');window.open(url,'_blank','noopener');st('Private POD link valid for 5 minutes.','ok');return}throw new Error('No POD file is available on this device or in Cloud')}catch(e){st(e.message||String(e),'error')}}
  function injectButton(){const host=$('#mani-bulkbar')||$('.mani-bulkbar')||$('#card-manifest .card-head')||$('#card-manifest');if(!host||$('#v7-pod-open'))return;const b=document.createElement('button');b.id='v7-pod-open';b.type='button';b.className='v7-pod-manifest-btn';b.textContent='📎 POD';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open()});host.appendChild(b)}
  function install(){injectButton();const target=$('#card-manifest');if(target)new MutationObserver(muts=>{if(!$('#v7-pod-open')&&muts.some(m=>m.addedNodes.length||m.removedNodes.length))injectButton()}).observe(target,{childList:true,subtree:true});window.openPOD=open}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
