(()=>{
'use strict';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
let activeFilter='all';
function manifestActive(){return $('#card-manifest')?.classList.contains('v7-active')||$('.v7-nav button[data-v7="manifest"]')?.classList.contains('active')}
function statusOf(el){const t=(el?.innerText||'').toLowerCase();if(t.includes('delivered'))return'delivered';if(t.includes('in transit'))return'in_transit';if(t.includes('exception'))return'exception';return'pending'}
function rows(){return matchMedia('(max-width:900px)').matches?$$('#card-manifest .mobile-manifest-item'):$$('#card-manifest tbody tr')}
function applyFilter(){rows().forEach(r=>{const ok=activeFilter==='all'||statusOf(r)===activeFilter;r.style.display=ok?'':'none'})}
function clickLegacy(kind){const card=$('#card-manifest');if(!card)return;const buttons=$$('button',card);const patterns={print80:/print\s*80/i,pdf:/print\s*a4|save\s*pdf/i,csv:/export\s*csv|csv/i,pod:/attach\s*pod/i,archive:/archive selected/i,bulk:/bulk update/i};const re=patterns[kind];const b=buttons.find(x=>re&&re.test((x.textContent||'').trim()));if(b){b.click();return}if(kind==='pod')$('#v7-pod-open')?.click()}
function ensureTools(){const card=$('#card-manifest');if(!card)return;let tools=$('#u-clean-tools',card);if(!tools){tools=document.createElement('div');tools.id='u-clean-tools';tools.innerHTML='<select id="u-clean-view" aria-label="Manifest view"><option value="operational">Operational view</option><option value="extended">Extended view</option></select><details><summary>Manifest tools ▾</summary><div class="u-menu"><button data-u="print80">Print 80 mm</button><button data-u="pdf">Print A4 / Save PDF</button><button data-u="csv">Export CSV</button><button data-u="pod">Attach POD photo/file</button><button data-u="archive" class="danger">Archive selected</button></div></details>';const head=$('.card-head',card);head?.after(tools);$('#u-clean-view',tools)?.addEventListener('change',e=>{document.body.classList.toggle('u-clean-extended',e.target.value==='extended');const wrap=$('.tbl-wrap,.table-wrap,.manifest-table-wrap',card);if(wrap)wrap.scrollLeft=0});tools.addEventListener('click',e=>{const b=e.target.closest('button[data-u]');if(!b)return;clickLegacy(b.dataset.u);const d=b.closest('details');if(d)d.open=false})}
let filters=$('#u-clean-filters',card);if(!filters){filters=document.createElement('div');filters.id='u-clean-filters';filters.innerHTML='<button class="active" data-f="all">All</button><button data-f="pending">Pending</button><button data-f="in_transit">In Transit</button><button data-f="delivered">Delivered</button>';tools?.after(filters);filters.addEventListener('click',e=>{const b=e.target.closest('button[data-f]');if(!b)return;activeFilter=b.dataset.f;$$('button[data-f]',filters).forEach(x=>x.classList.toggle('active',x===b));applyFilter()})}}
function cleanAddress(){const card=$('#card-manifest');if(!card)return;$$('.mobile-field',card).forEach(f=>{const lab=$('label',f);if(lab&&/^address$/i.test((lab.textContent||'').trim()))f.classList.add('u-hide-address')})}
function relabel(){const hs=$$('#card-manifest thead th');const labels=['','PICK ID','CUSTOMER / CONTACT','','PHONE','DATE / TIME','ITEMS (Ar)','DELIVERY (Ar)','COPIES','MM REF','PAYMENT','STATUS','ACTIONS'];hs.forEach((h,i)=>{if(labels[i]!==undefined&&labels[i]!=='' )h.textContent=labels[i]})}
function sync(){const active=manifestActive();document.body.classList.toggle('u-clean-manifest',active);if(!active){document.body.classList.remove('u-clean-extended');return}ensureTools();cleanAddress();relabel();applyFilter();if(!document.body.classList.contains('u-clean-extended')){const wrap=$('#card-manifest .tbl-wrap,#card-manifest .table-wrap,#card-manifest .manifest-table-wrap');if(wrap)wrap.scrollLeft=0}}
function bind(){if(document.documentElement.dataset.uCleanBound==='1')return;document.documentElement.dataset.uCleanBound='1';document.addEventListener('v7:viewchange',()=>setTimeout(sync,0));document.addEventListener('click',e=>{if(e.target.closest?.('.v7-nav button[data-v7],.v7-new'))setTimeout(sync,50)},true);const card=$('#card-manifest');if(card)new MutationObserver(()=>requestAnimationFrame(()=>{cleanAddress();if(manifestActive())applyFilter()})).observe(card,{childList:true,subtree:true});window.addEventListener('resize',()=>setTimeout(sync,60),{passive:true})}
function boot(){bind();sync();[200,600,1400,2600].forEach(ms=>setTimeout(sync,ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
