import assert from'node:assert/strict';
import{createServer}from'node:http';
import{readFile}from'node:fs/promises';
import{mkdtemp, readdir}from'node:fs/promises';
import{tmpdir}from'node:os';
import{join,resolve}from'node:path';
import{spawn}from'node:child_process';

const root=resolve('.'),server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),path=url.pathname.replace(/^\//,'')||'index.html',file=resolve(root,path),data=await readFile(file);res.writeHead(200,{'content-type':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html'});res.end(data)}catch{res.writeHead(404);res.end('not found')}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const port=server.address().port,debugPort=port+1,downloads=await mkdtemp(join(tmpdir(),'beta3-download-')),chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-sandbox','--disable-gpu',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${await mkdtemp(join(tmpdir(),'beta3-chrome-'))}`,`--window-size=1440,1000`],{stdio:'ignore'});const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{let target;for(let i=0;i<30&&!target;i++){try{target=await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(`http://127.0.0.1:${port}/labelonzeway-beta3/command/?v=browser-smoke`)}`,{method:'PUT'}).then(r=>r.json())}catch{await wait(100)}}assert(target,'Chrome debugging target did not start');const ws=new WebSocket(target.webSocketDebuggerUrl),pending=new Map(),events=[];let seq=0;ws.onmessage=event=>{const data=JSON.parse(event.data);if(data.id&&pending.has(data.id)){pending.get(data.id)(data);pending.delete(data.id)}else events.push(data)};await new Promise((ok,bad)=>{ws.onopen=ok;ws.onerror=bad});const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,response=>response.error?reject(Error(response.error.message)):resolve(response.result));ws.send(JSON.stringify({id,method,params}))});const evaluate=expression=>cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});await cdp('Runtime.enable');await cdp('Log.enable');await cdp('Network.enable');await cdp('Page.enable');await cdp('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await cdp('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('lz.beta3.profiles',JSON.stringify({legacy:'malformed'}));`});await cdp('Page.navigate',{url:`http://127.0.0.1:${port}/labelonzeway-beta3/command/?v=browser-smoke`});await wait(1200);const errors=events.filter(event=>event.method==='Runtime.exceptionThrown'||event.method==='Log.entryAdded'&&['error','warning'].includes(event.params.entry.level)||event.method==='Network.loadingFailed');assert.equal(errors.length,0,`startup browser errors: ${JSON.stringify(errors)}`);const click=async selector=>{const result=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)throw Error('missing ${selector}');el.click();return true})()`);assert.equal(result.result.value,true,`click failed: ${selector}`);await wait(120)};const visible=selector=>evaluate(`!!document.querySelector(${JSON.stringify(selector)})&&getComputedStyle(document.querySelector(${JSON.stringify(selector)})).display!=='none'`);
await click('[data-rail-toggle]');await click('[data-rail-toggle]');await click('[data-profiles]');assert.equal((await visible('[data-profile-dialog]')).result.value,true,'Profile Manager did not open');const before=await readdir(downloads);await click('[data-profile-export]');await wait(400);const after=await readdir(downloads);assert.equal(after.length,before.length+1,'row backup did not create exactly one download');assert.match(after[0],/^labelonzeway-.*-backup-\d{4}-\d{2}-\d{2}\.json$/);assert((await visible('[data-profile-dialog]')).result.value,'Profile Manager closed after export');await click('[data-profile-cancel]');await click('[data-book-backup]');await wait(300);assert.equal((await readdir(downloads)).length,after.length+1,'top-level JSON backup did not download');await click('[data-new-customer]');assert((await visible('[data-contact-editor]')).result.value,'contact drawer did not open');await click('[data-contact-cancel]');await click('[data-preview-open]');assert((await visible('[data-preview-dialog]')).result.value,'preview modal did not open');await click('[data-preview-close]');
await cdp('Page.navigate',{url:`http://127.0.0.1:${port}/labelonzeway-beta3/design-a/`});await wait(500);await click('[aria-label="Toggle prototype rail"]');await click('[aria-label="Open new customer drawer"]');assert((await visible('[data-demo-name]')).result.value,'Design A drawer did not open');await click('[data-demo-close]');await click('.proto-card');
await cdp('Page.navigate',{url:`http://127.0.0.1:${port}/labelonzeway-beta3/design-b/`});await wait(500);const beforeStep=(await evaluate(`document.querySelector('.step:nth-child(3)').classList.contains('active')`)).result.value;await click('.primary');const afterStep=(await evaluate(`document.querySelector('.step:nth-child(3)').classList.contains('active')`)).result.value;assert.equal(beforeStep,false);assert.equal(afterStep,true,'Design B Continue did not advance');await click('.secondary');assert.equal((await evaluate(`document.querySelector('.step:nth-child(2)').classList.contains('active')`)).result.value,true,'Design B Back did not respond');assert.equal(events.filter(event=>event.method==='Runtime.exceptionThrown'||event.method==='Network.loadingFailed').length,0,'browser errors occurred during interactions');ws.close();console.log(`browser smoke passed on http://127.0.0.1:${port}/labelonzeway-beta3/command/ and prototype routes`)}finally{chrome.kill('SIGTERM');server.close()}
