import assert from'node:assert/strict';
import{validPhone,validAddress,createCustomer,createParcel,statusOf,normalizeParcel,totals,pick,nextPick,collect,transition,upsertCustomer,searchCustomers,deleteCustomers,draftCollect,blankDraft,findDuplicate,mergeCustomer,deleteProfile,blankProfile,blankBatchRow,batchCollect,mergeBatchRows,selectBatchRows,deleteBatchRows,applyBatchCustomer,addBatchRowsToManifest}from'../app/core.js';
import{contactFromText,labelPdfBlob,manifestCsv,priceFromText,customersCsv,customersFromCsv}from'../app/operations.js';
assert(validPhone('0341234567'));assert(validPhone('0391234567'));assert(!validPhone('0311234567'));assert(!validPhone('0361234567'));assert(validAddress('Lot II 45, pres du marche'));assert(validAddress('Cité Ampefiloha'));assert(!validAddress('texte OCR aleatoire'));
const c=createCustomer({name:'Aina',phone:'0341234567',address:'Lot II 45'}),p=createParcel({qty:3,price:2000,ship:1000},c,7,new Date('2026-08-20T10:00:00Z'),[]);assert.equal(p.oid,'20260820-0001');assert.equal(p.cod,6000);assert.equal(collect(3,2000,''),6000);assert.equal(collect(3,2000,null),6000);assert.equal(p.deliveryStatus,'ready');assert.equal(statusOf({done:true,deliveryStatus:'ready'}),'delivered');assert.equal(normalizeParcel({done:true,deliveryStatus:'ready'}).deliveryStatus,'delivered');assert.equal(transition(transition(p,'in_transit'),'delivered').deliveryStatus,'delivered');assert.throws(()=>transition({done:true},'ready'));assert.throws(()=>transition(p,'exception',new Date(),''));assert.equal(nextPick([{oid:'20260102-0001'}],new Date('2026-01-02')),'20260102-0002');assert.equal(pick(9,new Date('2026-01-02')),'20260102-0009');
assert.deepEqual(totals([p]),{sales:6000,delivery:1000,cod:6000,total:7000});assert.equal(draftCollect({...blankDraft(),qty:2,price:3000}),6000);assert.equal(draftCollect(blankDraft()),'');assert.equal(draftCollect({...blankDraft(),price:3000,cod:0}),0);
const transitionMatrix={ready:['in_transit','exception'],in_transit:['delivered','exception'],exception:['in_transit','delivered'],delivered:[]};for(const[from,targets]of Object.entries(transitionMatrix)){for(const next of targets)assert.equal(transition({deliveryStatus:from},next,new Date(),'exception'===next?'required':'').deliveryStatus,next,`${from} should allow ${next}`);for(const next of Object.keys(transitionMatrix).filter(next=>next!==from&&!targets.includes(next)))assert.throws(()=>transition({deliveryStatus:from},next,new Date(),'required'),`${from} must reject ${next}`)}
const customers=[];upsertCustomer(customers,c);assert.equal(searchCustomers(customers,'aina').length,1);assert.equal(searchCustomers(customers,'lot ii').length,1);assert.throws(()=>upsertCustomer(customers,{...c,id:'other'}));const edited=upsertCustomer(customers,{...c,address:'Rue 1'});assert.equal(edited.address,'Rue 1');assert.equal(findDuplicate(customers,{...c,id:'x'}).id,c.id);assert.equal(deleteCustomers(customers,[c.id]).length,0);
const a=blankProfile(),b=blankProfile();assert.throws(()=>deleteProfile([a],a.id,a.id));assert.equal(deleteProfile([a,b],a.id,a.id).activeId,b.id);
const detected=contactFromText('Aina Rakoto\n034 123 4567\nLot II 45');assert.equal(detected.phone,'0341234567');assert.equal(detected.address,'Lot II 45');const pdf=labelPdfBlob(p,{name:'LZ'});assert(pdf.size>100);assert.equal(pdf.type,'application/pdf');assert(manifestCsv([p]).includes('Pick ID'));
const batchA=blankBatchRow({id:'a',contact:{name:'Aina',phone:'0341234567'},customerId:c.id,qty:2,price:3000,copies:2}),batchB=blankBatchRow({id:'b',contact:{name:'Aina',phone:'0341234567'},customerId:c.id,qty:1,price:3000});assert.equal(batchA.status,'queued');assert.equal(batchCollect(batchA),6000);assert.equal(batchCollect({...batchA,cod:4500}),4500);assert.equal(batchCollect({...batchA,price:'',cod:''}),'');assert.equal(priceFromText('Prix: 12 500 Ar'),12500);assert.equal(contactFromText('0311234567\nrandom words').phone,'');const merged=mergeBatchRows([batchA,batchB],['a','b']);assert.equal(merged.merged,1);assert.equal(merged.rows[0].qty,3);const other=blankBatchRow({id:'c',contact:{name:'Aina',phone:'0331234567'},customerId:c.id,qty:1,price:3000});assert.equal(mergeBatchRows([batchA,other],['a','c']).merged,0);const bp=createParcel({qty:batchA.qty,price:batchA.price,cod:batchA.cod,ship:''},c,0,new Date('2026-08-20'),[]);assert.equal(bp.oid,'20260820-0001');batchA.addedParcelIds=['already'];assert.throws(()=>{if(batchA.addedParcelIds.length)throw Error('duplicate')});
const selected=selectBatchRows([batchA,batchB],['a']);assert(selected[0].selected&&!selected[1].selected);assert.equal(deleteBatchRows(selected,['b']).length,1);assert.equal(applyBatchCustomer([batchB],['b'],c.id)[0].customerId,c.id);const created=addBatchRowsToManifest([batchB],['b'],[c],[],new Date('2026-08-20'));assert.equal(created.length,1);assert.equal(created[0].oid,'20260820-0001');
const imported=customersFromCsv(customersCsv([c]));assert.equal(imported[0].phone,c.phone);assert.equal(mergeCustomer(c,{...c,address:'',note:'new'}).address,c.address);
console.log('all deterministic core/operations tests passed');
