import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{prepareBackupRestore}from'../app/core.js';

const app=await readFile('app/app.js','utf8');
for(const phrase of['function profileBackup(profile)','app:\'LABELONZEWAY\',version:4','exportedAt:new Date().toISOString()','logoThermal','logoIncludesBusinessName','new Blob([content],{type:\'application/json;charset=utf-8\'})','URL.createObjectURL(blob)','document.body.append(anchor)','anchor.click()','anchor.remove()','setTimeout(()=>URL.revokeObjectURL(url),1000)','Backup downloaded successfully','Backup could not be downloaded:'])assert(app.includes(phrase),`backup exporter missing ${phrase}`);
assert(app.includes('data-profile-export="${esc(item.id)}"'),'profile rows must export their own IDs');assert(app.includes('downloadProfileBackup(item,response=>showProfileBackupResult(modal,response))'),'row export must preserve its modal and row profile');assert(app.includes('data.bookBackup!==undefined')&&app.includes('downloadProfileBackup(item,response=>{if(response.ok)toast'),'top-level JSON backup must use the same exporter');
assert.equal((app.match(/anchor\.click\(\)/g)||[]).length,1,'exporter must invoke one temporary download anchor');assert.match(app,/anchor\.remove\(\);setTimeout\(\(\)=>URL\.revokeObjectURL\(url\),1000\)/,'object URL revocation must be delayed');assert.match(app,/labelonzeway-\$\{sanitizeBackupName\(profile\.name\)\}-backup-\$\{new Date\(\)\.toISOString\(\)\.slice\(0,10\)\}\.json/,'filename must be sanitized and dated');
const shop={name:'LUZDM',phone:'+261 347698740 WHATSAPP',tagline:'FACEBOOK - INSTAGRAM',thanks:'Misaotra',logoThermal:'data:image/png;base64,logo',logoIncludesBusinessName:true,currency:'Ar',codLabel:'Collect',printerPort:9100},payload={app:'LABELONZEWAY',version:4,exportedAt:new Date().toISOString(),profile:{id:'luzdm',name:'LUZDM'},data:{shop,addr:[{id:'c1',name:'Customer'}],manifest:[{id:'p1',oid:'20260824-0001'}],archive:[],counter:1,labelVault:[],gateway:{},draft:{copies:1}}};
const restored=prepareBackupRestore(payload).profiles[0];assert.equal(restored.profile.name,'LUZDM');assert.deepEqual(restored.shop,shop);assert.equal(restored.customers.length,1);assert.equal(restored.manifest.length,1);assert.equal(restored.shop.logoIncludesBusinessName,true);console.log('profile backup exporter audit passed');
