export const PHONE=/^(032|033|034|035|037|038|039)\d{7}$/;
export const ADDRESS=/(?:\blot\b|\bparcelle\b|\bcit[eé]\b|\bb\.?p\.?\b|\brue\b|\bakaik[yi]\b|\bpr[eè]s\b|\barr[eê]t\b|\b[aà]\s*c[oô]t[eé]\b|\bacc[eè]s\b|\ben\s+face\b|\bquartier\b|\bavenue\b|\bimmeuble\b)/i;
const clean=v=>String(v??'').trim();
export const validPhone=p=>PHONE.test(clean(p).replace(/[\s.-]/g,''));
export const validAddress=a=>ADDRESS.test(clean(a).normalize('NFD').replace(/[\u0300-\u036f]/g,''));
export const uid=(prefix='id')=>`${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
export const statusOf=r=>(r?.done||r?.pod||r?.deliveryStatus==='delivered')?'delivered':(['ready','in_transit','exception'].includes(r?.deliveryStatus)?r.deliveryStatus:'ready');
export const normalizeParcel=r=>({...r,deliveryStatus:statusOf(r),done:statusOf(r)==='delivered',exceptionAt:statusOf(r)==='exception'?(r.exceptionAt||r.statusUpdatedAt||new Date().toISOString()):'',exceptionNote:statusOf(r)==='exception'?(r.exceptionNote||''):''});
export const pick=(n,date=new Date())=>`${date.toISOString().slice(0,10).replace(/-/g,'')}-${String(n).padStart(4,'0')}`;
export const nextPick=(rows,date=new Date())=>{const day=date.toISOString().slice(0,10).replace(/-/g,''),used=new Set((rows||[]).map(r=>r.oid).filter(x=>String(x).startsWith(`${day}-`)));let n=1;while(used.has(`${day}-${String(n).padStart(4,'0')}`))n++;return `${day}-${String(n).padStart(4,'0')}`};
export const collect=(qty,price,manual)=>manual===''||manual==null?Math.max(1,Number(qty)||1)*Math.max(0,Number(price)||0):Math.max(0,Number(manual));
export const draftCollect=d=>d?.cod!==''&&d?.cod!=null?Math.max(0,Number(d.cod)||0):d?.price===''||d?.price==null?'':collect(d.qty,d.price,'');
export const blankDraft=()=>({customerId:'',qty:1,copies:1,price:'',cod:'',ship:'',salesFee:'',deliverAt:'',deliverTime:'',pay:'COD',notes:'',reference:'',scan:null});
export const blankBatchRow=(input={})=>({id:input.id||uid('batch'),image:input.image||'',fileName:input.fileName||'',selected:false,status:input.status||'queued',contact:input.contact||null,contactOpen:input.contactOpen??false,customerId:input.customerId||'',qty:input.qty??1,copies:input.copies??1,price:input.price??'',cod:input.cod??'',ship:input.ship??'',salesFee:input.salesFee??'',pay:input.pay||'COD',addedParcelIds:input.addedParcelIds||[],printed:!!input.printed,error:input.error||''});
export const batchCollect=row=>row?.cod!==''&&row?.cod!=null?Math.max(0,Number(row.cod)||0):row?.price===''||row?.price==null?'':collect(row.qty,row.price,'');
export const selectBatchRows=(rows,ids,selected=true)=>(rows||[]).map(r=>new Set(ids).has(r.id)?{...r,selected}:r);
export const deleteBatchRows=(rows,ids)=>(rows||[]).filter(r=>!new Set(ids).has(r.id));
export const applyBatchCustomer=(rows,ids,customerId)=>(rows||[]).map(r=>new Set(ids).has(r.id)?{...r,customerId,status:'ready'}:r);
export function addBatchRowsToManifest(rows,ids,customers,manifest,date=new Date(),labelShop={}){const idSet=new Set(ids),created=[];for(const row of rows||[]){if(!idSet.has(row.id)||row.addedParcelIds?.length)continue;const customer=(customers||[]).find(c=>c.id===row.customerId);if(!customer)throw Error('Choose or confirm a customer first');if(row.price==='')throw Error('Price not found — enter it manually before adding');const parcel=createParcel({qty:row.qty,price:row.price,cod:row.cod,ship:row.ship,salesFee:row.salesFee,pay:row.pay},customer,0,date,[...(manifest||[]),...created],labelShop);created.push(parcel)}return created}
export function mergeBatchRows(rows,ids){const chosen=(rows||[]).filter(r=>new Set(ids).has(r.id)),groups=new Map();for(const r of chosen){if(!r.customerId||!r.contact?.phone)continue;const k=`${r.customerId}|${String(r.contact.phone).replace(/\D/g,'')}`;groups.set(k,[...(groups.get(k)||[]),r])}const remove=new Set(),merged=[];for(const group of groups.values()){if(group.length<2)continue;const [first,...rest]=group;const same=group.every(r=>String(r.contact.phone).replace(/\D/g,'')===String(first.contact.phone).replace(/\D/g,''));if(!same)continue;const out={...first,qty:group.reduce((n,r)=>n+Math.max(1,Number(r.qty)||1),0),copies:group.reduce((n,r)=>n+Math.max(1,Number(r.copies)||1),0),price:group.every(r=>String(r.price)===String(first.price))?first.price:'',cod:group.every(r=>r.cod===''||r.cod==null)?'':group.reduce((n,r)=>n+(Number(batchCollect(r))||0),0),ship:group.reduce((n,r)=>n+(Number(r.ship)||0),0),salesFee:group.reduce((n,r)=>n+(Number(r.salesFee)||0),0),status:'ready'};rest.forEach(r=>remove.add(r.id));merged.push(out)}return{rows:(rows||[]).filter(r=>!remove.has(r.id)).map(r=>merged.find(m=>m.id===r.id)||r),merged:merged.length}}
export function createCustomer(input={}){const phone=clean(input.phone).replace(/[\s.-]/g,'');if(!clean(input.name))throw Error('Customer name is required');if(phone&&!validPhone(phone))throw Error('Use a valid Malagasy mobile number (032–039, excluding 036)');if(clean(input.address)&&!validAddress(input.address))throw Error('Address needs an operational address indicator (Lot, Rue, Cité, etc.)');return{id:input.id||uid('customer'),name:clean(input.name),phone,area:clean(input.area),address:clean(input.address),note:clean(input.note),createdAt:input.createdAt||new Date().toISOString()}}
export const customerKey=c=>`${clean(c?.name).toLowerCase()}|${clean(c?.phone).replace(/\D/g,'')}`;
export const findDuplicate=(list,c,except=c?.id)=>(list||[]).find(x=>x.id!==except&&customerKey(x)===customerKey(c));
export const mergeCustomer=(existing,incoming)=>({...incoming,...existing,id:existing.id,name:existing.name||incoming.name,phone:existing.phone||incoming.phone,area:existing.area||incoming.area,address:existing.address||incoming.address,note:existing.note||incoming.note});
export const searchCustomers=(list,q)=>{q=clean(q).toLowerCase();return !q?[...(list||[])]:[...(list||[])].filter(c=>[c.name,c.phone,c.area,c.address].join(' ').toLowerCase().includes(q))};
export function upsertCustomer(list,input){const c=createCustomer(input),duplicate=findDuplicate(list,c,c.id);if(duplicate)throw Error(`Duplicate customer: ${duplicate.name}`);const i=list.findIndex(x=>x.id===c.id);i<0?list.push(c):list.splice(i,1,c);return c}
export const deleteCustomers=(list,ids)=>{const remove=new Set(ids);return(list||[]).filter(c=>!remove.has(c.id))};
export function createParcel(draft,customer,counter=0,date=new Date(),rows=[],labelShop={}){if(!customer)throw Error('Select a saved customer');const qty=Math.max(1,Number(draft.qty)||1),copies=Math.max(1,Number(draft.copies)||1),price=Math.max(0,Number(draft.price)||0),salesFee=Math.max(0,Number(draft.salesFee)||0),ship=Math.max(0,Number(draft.ship)||0),cod=collect(qty,price,draft.cod),oid=nextPick(rows,date),snapshot=Object.keys(labelShop||{}).length?{labelShop:resolveLabelShop(labelShop)}:{};return normalizeParcel({id:uid('parcel'),oid,rec:{...customer},qty,copies,price,salesFee,cod,ship,pay:draft.pay||'COD',deliverAt:draft.deliverAt||'',deliverTime:draft.deliverTime||'',notes:clean(draft.notes),reference:clean(draft.reference),addedAt:date.toISOString(),deliveryStatus:'ready',done:false,paid:false,...snapshot})}
export const parcelSales=p=>Math.max(0,Number(p?.qty)||1)*Math.max(0,Number(p?.price)||0)+Math.max(0,Number(p?.salesFee)||0);
export const parcelCollect=p=>Math.max(0,Number(p?.cod)||0);
export const totals=rows=>(rows||[]).reduce((x,row)=>{const r=normalizeParcel(row);x.sales+=parcelSales(r);x.delivery+=Number(r.ship)||0;x.cod+=parcelCollect(r);x.total+=parcelSales(r)+(Number(r.ship)||0);return x},{sales:0,delivery:0,cod:0,total:0});
export function transition(row,next,now=new Date(),note=''){const current=statusOf(row),allowed={ready:['in_transit','exception'],in_transit:['delivered','exception'],exception:['in_transit','delivered'],delivered:[]};if(current==='delivered'&&next!=='delivered')throw Error('Delivered parcels cannot regress');if(!allowed[current].includes(next)&&next!==current)throw Error(`Cannot change ${current} to ${next}`);if(next==='exception'&&!clean(note))throw Error('An exception note is required');return normalizeParcel({...row,deliveryStatus:next,done:next==='delivered',statusUpdatedAt:now.toISOString(),exceptionAt:next==='exception'?now.toISOString():'',exceptionNote:next==='exception'?clean(note):''})}
export const blankProfile=()=>({id:uid('profile'),name:'My delivery profile',currency:'Ar',createdAt:new Date().toISOString()});
export const blankGatewaySettings=()=>({gatewayUrl:'http://127.0.0.1:8765',lanGatewayUrl:'http://192.168.100.14:8765',printerIp:'',printerPort:9100});
export function resolveLabelShop(shop={},profile={}){const text=value=>clean(value),businessName=text(shop?.name),profileName=text(profile?.name),hasBusinessName=typeof shop?.hasBusinessName==='boolean'?shop.hasBusinessName:!!(businessName||profileName);return{name:businessName||profileName||'LABELONZEWAY',hasBusinessName,phone:text(shop?.phone),tagline:text(shop?.tagline),thanks:text(shop?.thanks),currency:text(shop?.currency)||'Ar',codLabel:text(shop?.codLabel)||'COLLECT',logoThermal:typeof shop?.logoThermal==='string'?shop.logoThermal:'',logoIncludesBusinessName:shop?.logoIncludesBusinessName===true}}
export const parcelLabelShop=(parcel,shop={},profile={})=>parcel?.labelShop?resolveLabelShop(parcel.labelShop):resolveLabelShop(shop,profile);
export function deleteProfile(profiles,activeId,id){if((profiles||[]).length<2)throw Error('The final profile cannot be deleted');const target=profiles.find(p=>p.id===id);if(!target)throw Error('Profile not found');const next=profiles.filter(p=>p.id!==id);return{profiles:next,activeId:activeId===id?next[0].id:activeId,deleted:target}}
export function storage(profileId){const read=(k,d)=>{try{const v=localStorage.getItem(`lz.theta77.${profileId}.${k}`);return v?JSON.parse(v):d}catch{return d}},write=(k,v)=>localStorage.setItem(`lz.theta77.${profileId}.${k}`,JSON.stringify(v));const state={shop:read('shop',{}),addr:read('addr',[]),manifest:read('mani',[]).map(normalizeParcel),archive:read('arch',[]),counter:Number(read('ctr',0))||0,labelVault:read('labels',[]),draft:{...blankDraft(),...read('draft',{})},batch:read('batch',[]),gateway:{...blankGatewaySettings(),...read('gateway',{})}};return{state,save(){[['shop',state.shop],['addr',state.addr],['mani',state.manifest],['arch',state.archive],['ctr',state.counter],['labels',state.labelVault],['draft',state.draft],['batch',state.batch],['gateway',state.gateway]].forEach(([k,v])=>write(k,v))}}}
const importText=v=>clean(v).replace(/\s+/g,' '),importPhone=v=>importText(v).replace(/^(?:\+?261)/,'0').replace(/\D/g,'');
export function importTrustedCustomers(existing=[],rows=[]){const customers=(existing||[]).map(x=>({...x})),errors=[];let imported=0,merged=0,skipped=0,incomplete=0,probableDuplicates=0;const text=v=>importText(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');for(const raw of rows||[]){const row=raw?.rowNumber||raw?.row||0,name=importText(raw?.name),phone=importPhone(raw?.phone),area=importText(raw?.area),address=importText(raw?.address),note=importText(raw?.note),sourceCustomerId=importText(raw?.sourceCustomerId),sourceProfile=importText(raw?.sourceProfile);if(!name){errors.push({row,reason:'Name is required'});continue}if(phone&&!validPhone(phone)){errors.push({row,reason:`Unsupported Malagasy phone prefix: ${phone.slice(0,3)}`});continue}const incoming={id:uid('customer'),name,phone,area,address,note,sourceCustomerId,sourceProfile,createdAt:new Date().toISOString(),incompleteAddress:!address};const duplicate=customers.find(x=>(sourceCustomerId&&importText(x.sourceCustomerId)===sourceCustomerId)||(phone&&importPhone(x.phone)===phone)||(!phone&&text(x.name)===text(name)&&text(x.address)===text(address)&&!!address));if(!duplicate){customers.push(incoming);imported++;if(!address)incomplete++;continue}const sourceMatch=sourceCustomerId&&importText(duplicate.sourceCustomerId)===sourceCustomerId,phoneMatch=phone&&importPhone(duplicate.phone)===phone,probable=!sourceMatch&&!phoneMatch&&text(duplicate.name)===text(name)&&text(duplicate.address)===text(address);if(probable)probableDuplicates++;const next=mergeCustomer(duplicate,incoming);next.sourceCustomerId=duplicate.sourceCustomerId||sourceCustomerId;next.sourceProfile=duplicate.sourceProfile||sourceProfile;next.incompleteAddress=!next.address;const changed=['name','phone','area','address','note','sourceCustomerId','sourceProfile'].some(key=>String(next[key]||'')!==String(duplicate[key]||''));Object.assign(duplicate,next);if(changed)merged++;else skipped++;}return{customers,imported,merged,skipped,failed:errors.length,incomplete,probableDuplicates,errors}}
const backupArray=(value,name)=>{if(value==null)return[];if(!Array.isArray(value))throw Error(`${name} must be an array`);return value};
export function prepareBackupRestore(text){let payload;try{payload=typeof text==='string'?JSON.parse(text):text}catch{throw Error('Backup is not valid JSON')}if(!payload||typeof payload!=='object'||Array.isArray(payload))throw Error('Backup must be an object');if(payload.app&&payload.app!=='LABELONZEWAY')throw Error('Unsupported backup application');const source=payload.data&&typeof payload.data==='object'?payload.data:payload;const rawProfiles=Array.isArray(payload.profiles)&&payload.profiles.length?payload.profiles:[{profile:payload.profile||{id:payload.profileId||'restored-profile',name:payload.profile?.name||'Restored profile'},data:source}];const profiles=rawProfiles.map((entry,index)=>{const profile=entry.profile||entry,data=entry.data||payload.dataByProfile?.[profile?.id]||source;if(!profile||typeof profile!=='object'||!data||typeof data!=='object'||Array.isArray(data))throw Error(`Profile ${index+1} is malformed`);const id=importText(profile.id)||`restored-profile-${index+1}`,name=importText(profile.name)||'Restored profile',customers=backupArray(data.addr??data.customers,'Customers'),manifest=backupArray(data.manifest??data.mani,'Manifest'),archive=backupArray(data.archive??data.arch,'Archive'),labelVault=backupArray(data.labelVault??data.labels,'Label vault');return{profile:{...profile,id,name},shop:data.shop&&typeof data.shop==='object'?data.shop:{},customers,manifest,archive,labelVault,counter:Math.max(0,Number(data.counter??data.ctr)||0),gateway:data.gateway&&typeof data.gateway==='object'?data.gateway:{},draft:data.draft&&typeof data.draft==='object'?data.draft:{}}});if(!profiles.length)throw Error('Backup contains no profiles');return{profiles,preview:{profiles:profiles.length,customers:profiles.reduce((n,p)=>n+p.customers.length,0),parcels:profiles.reduce((n,p)=>n+p.manifest.length+p.archive.length+p.labelVault.length,0),manifests:profiles.reduce((n,p)=>n+p.manifest.length,0),settings:profiles.filter(p=>Object.keys(p.shop).length||Object.keys(p.gateway).length).length}};}
const prepareBackupRestoreLegacy=prepareBackupRestore,backupAdapters=Object.freeze({3:payload=>({...payload,app:'LABELONZEWAY'}),4:payload=>({...payload,app:'LABELONZEWAY'})});
export function validateBackupEnvelope(payload){const app=String(payload?.app??'').trim().toUpperCase();if(app!=='LABELONZEWAY')throw Error('Unsupported backup application');const version=Number(payload?.version);if(!Number.isInteger(version)||!backupAdapters[version])throw Error(`Unsupported backup version ${String(payload?.version??'')}`);return{app:'LABELONZEWAY',version,exportedAt:typeof payload.exportedAt==='string'?payload.exportedAt:'',payload:backupAdapters[version](payload)}}
prepareBackupRestore=function(text){let payload;try{payload=typeof text==='string'?JSON.parse(text):text}catch{throw Error('Backup is not valid JSON')}if(!payload||typeof payload!=='object'||Array.isArray(payload))throw Error('Backup must be an object');const envelope=validateBackupEnvelope(payload),plan=prepareBackupRestoreLegacy(envelope.payload);return{...plan,metadata:{app:envelope.app,version:envelope.version,exportedAt:envelope.exportedAt,preferences:envelope.payload.preferences??envelope.payload.data?.preferences??null}}};
