import{validPhone,validAddress,parcelCollect,parcelSales,parcelLabelShop}from'./core.js';
export const THERMAL_LOGO_MAX_WIDTH=320,THERMAL_LOGO_MAX_HEIGHT=96;
export function thermalRasterEscPos(width,height,blackPixels){width=Number(width);height=Number(height);if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>THERMAL_LOGO_MAX_WIDTH||height>THERMAL_LOGO_MAX_HEIGHT)throw Error('Thermal logo dimensions must be within 320 × 96 dots');if(!blackPixels||blackPixels.length!==width*height)throw Error('Thermal logo pixels do not match its dimensions');const bytesPerRow=Math.ceil(width/8),out=new Uint8Array(8+bytesPerRow*height);out.set([0x1d,0x76,0x30,0x00,bytesPerRow&255,bytesPerRow>>8,height&255,height>>8]);for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(blackPixels[y*width+x])out[8+y*bytesPerRow+(x>>3)]|=0x80>>(x&7);return out}
export function rasterBitmapEscPos(width,height,blackPixels){width=Number(width);height=Number(height);if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>LABEL_DOTS||!blackPixels||blackPixels.length!==width*height)throw Error('Label raster dimensions are invalid');const bytesPerRow=Math.ceil(width/8),out=new Uint8Array(8+bytesPerRow*height);out.set([0x1d,0x76,0x30,0x00,bytesPerRow&255,bytesPerRow>>8,height&255,height>>8]);for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(blackPixels[y*width+x])out[8+y*bytesPerRow+(x>>3)]|=0x80>>(x&7);return out}
export const LABEL_DOTS=576,LABEL_MARGIN=10,LABEL_CONTENT_WIDTH=556;
export const asciiMoney=(value,currency='Ar')=>`${String(currency||'Ar').replace(/[^A-Za-z0-9]/g,'')||'Ar'} ${Math.max(0,Number(value)||0).toLocaleString('en-US').replace(/,/g,' ')}`;
export const wrapLabelText=(value,maxChars=35)=>{const words=String(value??'').trim().split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){if(!line){line=word;continue}if(`${line} ${word}`.length<=maxChars)line+=` ${word}`;else{lines.push(line);line=word}}if(line)lines.push(line);return lines.length?lines:['—']};
export function createLabelLayout(parcel,shop={},logo={}){const label=parcelLabelShop(parcel,shop),date=new Date(parcel.addedAt||Date.now()),created=date.toLocaleString('en-GB',{hour12:false}).replace(',',''),delivery=parcel.deliverAt||'Not scheduled',recipient=parcel.rec||{},name=wrapLabelText(recipient.name||'Recipient',35),phone=wrapLabelText(recipient.phone||'No phone',35),address=wrapLabelText(recipient.address||'No address',42),payment=String(parcel.pay||'COD'),logoWidth=Math.min(340,LABEL_CONTENT_WIDTH),logoHeight=logo.width&&logo.height?Math.max(1,Math.round(logoWidth*logo.height/logo.width)):0;const sections=[{type:'header',logo:!!logoWidth&&!!logoHeight,logoWidth,logoHeight,name:label.name,phone:label.phone,tagline:label.tagline},{type:'meta',pickId:parcel.oid||'—',created},{type:'delivery',date:delivery},{type:'recipient',name,phone,address},{type:'collect',amount:asciiMoney(parcel.cod,label.currency),items:`Item ${asciiMoney(Number(parcel.qty||1)*Number(parcel.price||0),label.currency)}`,delivery:`Delivery ${asciiMoney(parcel.ship,label.currency)}`,payment:`Payment ${payment}`},{type:'footer',thanks:label.thanks||''}];let height=18;if(logoHeight)height+=logoHeight+12;else height+=label.name?34:18;if(label.phone)height+=25;if(label.tagline)height+=25;height+=54+42+28+(name.length+phone.length+address.length)*30+112+(label.thanks?50:18);return{width:LABEL_DOTS,margin:LABEL_MARGIN,contentWidth:LABEL_CONTENT_WIDTH,height:Math.max(320,height),sections,logo:logo.src||'',logoIncludesBusinessName:!!label.logoIncludesBusinessName}}
export function priceFromText(text){const m=String(text||'').match(/(?:prix|price|montant|ar)\s*[:=-]?\s*([0-9][0-9 .]{1,12})/i);return m?Number(m[1].replace(/\D/g,''))||'':''}
export function contactFromText(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),all=lines.join(' '),match=all.match(/(?:\+261|0)(?:[ .-]?\d){9}/)?.[0]||'',phone=match.replace(/^\+261/,'0').replace(/[ .-]/g,''),address=lines.find(validAddress)||'',name=lines.find(x=>/^[A-Za-zÀ-ÿ' -]{3,40}$/.test(x)&&x!==address)||'';return{phone:validPhone(phone)?phone:'',address,name,price:priceFromText(all),text:String(text||'')}}
export async function ocrPhoto(file){if(!file)throw Error('Choose a photo first');if(!window.Tesseract)await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>bad(Error('OCR engine could not load. Check your connection and try again.'));document.head.append(s)});const result=await window.Tesseract.recognize(file,'eng+fra');return contactFromText(result.data.text)}
const escPdf=s=>String(s??'').replace(/[\\()]/g,'\\$&').replace(/[^\x20-\x7e]/g,'?');
export function labelPdfBlob(parcel,shop={}){const label=parcelLabelShop(parcel,shop),amount=value=>`${label.currency} ${Number(value||0).toLocaleString()}`,lines=[label.name,label.phone,label.tagline,parcel.oid,parcel.rec?.name||'',parcel.rec?.phone||'',parcel.rec?.address||'',`QTY ${parcel.qty||1}  ${label.codLabel} ${amount(parcelCollect(parcel))}`,`DELIVERY ${amount(parcel.ship)}`,parcel.reference?`REF ${parcel.reference}`:'',label.thanks].filter(Boolean);const stream=`BT /F1 10 Tf 10 270 Td ${lines.map((x,i)=>`${i?'0 -15 Td ':''}(${escPdf(x)}) Tj`).join(' ')} ET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 204 288] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offset=[0];objects.forEach((o,i)=>{offset.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offset.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
export function labelRasterPdfBlob(canvas){const data=canvas.toDataURL('image/jpeg',.92).split(',')[1],binary=atob(data),jpeg=Uint8Array.from(binary,char=>char.charCodeAt(0)),width=canvas.width,height=canvas.height,content=`q ${width} 0 0 ${height} 0 0 cm /Im0 Do Q`,objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>',`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`,`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n${String.fromCharCode(...jpeg)}\nendstream`,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let pdf='%PDF-1.4\n',offset=[0];objects.forEach((object,index)=>{offset.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offset.slice(1).map(value=>`${String(value).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
export async function labelPngBlob(parcel,shop={}){const label=parcelLabelShop(parcel,shop),amount=value=>`${label.currency} ${Number(value||0).toLocaleString()}`,canvas=document.createElement('canvas');canvas.width=576;canvas.height=820;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,576,820);c.fillStyle='#111';c.font='bold 30px monospace';c.fillText(label.name,28,54);c.font='bold 38px monospace';c.fillText(parcel.oid||'',28,115);c.strokeStyle='#111';c.setLineDash([8,6]);c.beginPath();c.moveTo(28,140);c.lineTo(548,140);c.stroke();c.setLineDash([]);c.font='25px monospace';const lines=[label.phone,label.tagline,parcel.rec?.name,parcel.rec?.phone,parcel.rec?.address,`Qty: ${parcel.qty||1}`,`${label.codLabel}: ${amount(parcelCollect(parcel))}`,`Delivery: ${amount(parcel.ship)}`,parcel.reference&&`Ref: ${parcel.reference}`,label.thanks].filter(Boolean);lines.forEach((l,i)=>c.fillText(String(l).slice(0,34),28,190+i*48));return new Promise(ok=>canvas.toBlob(b=>ok(b),'image/png'))}
export function manifestCsv(rows){const h=['Pick ID','Customer','Address','Phone','Sales','Delivery','COD','Payment','Status'];return[h,...rows.map(r=>[r.oid,r.rec?.name,r.rec?.address,r.rec?.phone,parcelSales(r),r.ship,parcelCollect(r),r.pay,r.deliveryStatus])].map(a=>a.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
const detectDelimiter=text=>{const first=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/,1)[0]||'';let best=',',bestCount=-1;for(const delimiter of[';',',','\t','|']){let count=0,quote=false;for(const ch of first){if(ch==='"')quote=!quote;else if(ch===delimiter&&!quote)count++}if(count>bestCount){best=delimiter;bestCount=count}}return best};
const csvRows=(text,delimiter=detectDelimiter(text))=>{const rows=[],row=[],value=[];let quote=false;for(let i=0,s=String(text||'').replace(/^\uFEFF/,'');i<s.length;i++){const ch=s[i],next=s[i+1];if(ch==='"'){if(quote&&next==='"'){value.push('"');i++}else quote=!quote;continue}if(!quote&&ch===delimiter){row.push(value.join(''));value.length=0;continue}if(!quote&&(ch==='\n'||ch==='\r')){if(ch==='\r'&&next==='\n')i++;row.push(value.join(''));value.length=0;if(row.some(cell=>cell!==''))rows.push(row.splice(0));else row.length=0;continue}value.push(ch)}if(quote)throw Error('Unclosed quoted CSV field');row.push(value.join(''));if(row.some(cell=>cell!==''))rows.push(row);return rows};
export function customersFromCsv(text){const raw=String(text||''),encoding=raw.startsWith('\uFEFF')?'UTF-8 BOM':'UTF-8',delimiter=detectDelimiter(raw),[head,...data]=csvRows(raw,delimiter),normalize=v=>String(v??'').replace(/^\uFEFF/,'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(),keys=(head||[]).map(normalize),errors=[];const field=(row,names)=>row[names.map(name=>keys.indexOf(normalize(name))).find(index=>index>=0)]||'',trim=v=>String(v??'').trim(),phone=v=>trim(v).replace(/^(?:\+?261)/,'0').replace(/[^\d]/g,'');const rows=data.map((row,index)=>({rowNumber:index+2,sourceProfile:trim(field(row,['Profile'])),sourceCustomerId:trim(field(row,['Customer ID'])),name:trim(field(row,['Name','Nom','Customer','Client','Recipient'])),phone:phone(field(row,['Phone','Telephone','Mobile','Tel','Finday'])),area:trim(field(row,['Area / City','Area','City','Ville','Zone','Quartier'])),address:trim(field(row,['Address','Adresse','Adiresy','Street','Addr'])),note:trim(field(row,['Note','Notes','Remark','Observation']))})).filter(row=>Object.values(row).some(value=>String(value).trim()));return{encoding,delimiter,columns:(head||[]).length,found:rows.length,rows,errors}}
export function downloadBlob(blob,name){if(!blob||blob.size<1)throw Error('File generation failed');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);return a.href}
export async function shareFile(blob,name,title='LabelOnZeWay label'){if(!blob||blob.size<1)throw Error('File generation failed');const file=new File([blob],name,{type:blob.type});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title,files:[file]});return'Native share opened'}throw Error('Native file sharing is unavailable on this browser. Download the file instead.')}
export const whatsappLink=parcel=>`https://wa.me/?text=${encodeURIComponent(`LabelOnZeWay ${parcel.oid}: ${location.origin}${location.pathname.replace(/\/(command|guided|rider|tracking)\/?$/,'')}tracking/?pick=${encodeURIComponent(parcel.oid)}`)}`;
export function customersCsv(rows){return[['Name','Phone','Area','Address','Note'],...(rows||[]).map(c=>[c.name,c.phone,c.area,c.address,c.note])].map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
export function importErrorsCsv(errors=[]){return[['Row','Reason'],...errors.map(error=>[error.row,error.reason])].map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
