export const PHONE=/^(032|033|034|035|037|038|039)\d{7}$/;
export const ADDRESS=/(?:\blot\b|\bparcelle\b|\bcit[eé]\b|\bb\.?p\.?\b|\brue\b|\bakaik[yi]\b|\bpr[eè]s\b|\barr[eê]t\b|\b[aà]\s*c[oô]t[eé]\b|\bacc[eè]s\b|\ben\s+face\b)/i;
export const statusOf=r=>r.deliveryStatus||((r.done||r.pod)?'delivered':'ready');
export const normalizeParcel=r=>({...r,deliveryStatus:statusOf(r),done:statusOf(r)==='delivered'});
export const validPhone=p=>PHONE.test(String(p||'').replace(/[\s.-]/g,''));
export const validAddress=a=>ADDRESS.test(String(a||'').normalize('NFD').replace(/[\u0300-\u036f]/g,''));
export const totals=rows=>(rows||[]).reduce((x,r)=>{x.sales+=Number(r.cod||r.price||0);x.delivery+=Number(r.ship||0);x.total+=Number(r.cod||r.price||0)+Number(r.ship||0);return x},{sales:0,delivery:0,total:0});
export const pick=(n,date=new Date())=>`${date.toISOString().slice(0,10).replace(/-/g,'')}-${String(n).padStart(4,'0')}`;
export const collect=(qty,price,manual)=>manual===''||manual==null?Math.max(1,Number(qty)||1)*Math.max(0,Number(price)||0):Math.max(0,Number(manual));
export const transition=(row,next,now=new Date())=>{const current=statusOf(row),allowed={ready:['in_transit','exception'],in_transit:['delivered','exception'],exception:['in_transit','delivered'],delivered:[]};if(current==='delivered'&&next!=='delivered')throw Error('Delivered parcels cannot regress');if(!allowed[current].includes(next)&&next!==current)throw Error(`Cannot change ${current} to ${next}`);return {...normalizeParcel(row),deliveryStatus:next,done:next==='delivered',statusUpdatedAt:now.toISOString()}};
export function createCustomer(input){const phone=String(input.phone||'').replace(/[\s.-]/g,'');if(!String(input.name||'').trim())throw Error('Customer name is required');if(phone&&!validPhone(phone))throw Error('Use a valid Malagasy mobile number');if(input.address&&!validAddress(input.address))throw Error('Address needs an operational address indicator');return {id:input.id||`a${Date.now()}${Math.random().toString(36).slice(2,6)}`,name:String(input.name).trim(),phone,area:String(input.area||'').trim(),address:String(input.address||'').trim(),note:String(input.note||'').trim()}}
export const customerKey=c=>`${String(c.name||'').trim().toLowerCase()}|${String(c.phone||'').replace(/\D/g,'')}`;
export const findDuplicate=(list,c,except)=>list.find(x=>x.id!==except&&customerKey(x)===customerKey(c));
export const searchCustomers=(list,q)=>{q=String(q||'').toLowerCase().trim();return !q?list:list.filter(c=>[c.name,c.phone,c.area,c.address].join(' ').toLowerCase().includes(q))};
export function upsertCustomer(list,input){const c=createCustomer(input),duplicate=findDuplicate(list,c,c.id);if(duplicate)throw Error('A customer with the same name and phone already exists');const i=list.findIndex(x=>x.id===c.id);if(i<0)list.push(c);else list[i]=c;return c}
export const deleteCustomers=(list,ids)=>list.filter(c=>!new Set(ids).has(c.id));
export const blankDraft=()=>({customerId:'',qty:1,price:'',cod:'',ship:'',deliverAt:'',deliverTime:'',pay:'COD',notes:'',scan:null});
export const draftCollect=d=>d.cod!==''?Number(d.cod):d.price===''?'':Math.max(1,Number(d.qty)||1)*Number(d.price);
export function createParcel(draft,customer,counter,date=new Date()){const qty=Math.max(1,Number(draft.qty)||1),price=Math.max(0,Number(draft.price)||0),ship=Math.max(0,Number(draft.ship)||0),cod=draft.cod==null?price*qty:Math.max(0,Number(draft.cod));return normalizeParcel({id:`r${Date.now()}${Math.random().toString(36).slice(2,6)}`,oid:pick(counter+1,date),rec:customer,qty,price,cod,ship,pay:draft.pay||'COD',deliverAt:draft.deliverAt||'',deliverTime:draft.deliverTime||'',addedAt:date.toISOString(),deliveryStatus:'ready',done:false,paid:false})}
export function storage(profileId){const read=(k,d)=>{try{const v=localStorage.getItem(`${profileId}.${k}`);return v?JSON.parse(v):d}catch{return d}};const write=(k,v)=>localStorage.setItem(`${profileId}.${k}`,JSON.stringify(v));const state={shop:read('shop',{}),addr:read('addr',[]),manifest:read('mani',[]).map(normalizeParcel),archive:read('arch',[]),counter:Number(read('ctr',0))||0,labelVault:read('labels',[]),draft:{...blankDraft(),...read('draft',{})}};return {state,save(){write('shop',state.shop);write('addr',state.addr);write('mani',state.manifest);write('arch',state.archive);write('ctr',state.counter);write('labels',state.labelVault);write('draft',state.draft)}}}
