export const PHONE=/^(032|033|034|035|037|038|039)\d{7}$/;
export const ADDRESS=/(?:\blot\b|\bparcelle\b|\bcit[eé]\b|\bb\.?p\.?\b|\brue\b|\bakaik[yi]\b|\bpr[eè]s\b|\barr[eê]t\b|\b[aà]\s*c[oô]t[eé]\b|\bacc[eè]s\b|\ben\s+face\b|\bquartier\b|\bavenue\b|\bimmeuble\b)/i;
const clean=v=>String(v??'').trim();
export const validPhone=p=>PHONE.test(clean(p).replace(/[\s.-]/g,''));
export const validAddress=a=>ADDRESS.test(clean(a).normalize('NFD').replace(/[\u0300-\u036f]/g,''));
export const uid=(prefix='id')=>`${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
export const statusOf=r=>(r?.done||r?.pod||r?.deliveryStatus==='delivered')?'delivered':(['ready','in_transit','exception'].includes(r?.deliveryStatus)?r.deliveryStatus:'ready');
export const normalizeParcel=r=>({...r,deliveryStatus:statusOf(r),done:statusOf(r)==='delivered',exceptionAt:statusOf(r)==='exception'?(r.exceptionAt||r.statusUpdatedAt||new Date().toISOString()):'',exceptionNote:statusOf(r)==='exception'?(r.exceptionNote||''):''});
export const pick=(n,date=new Date())=>`${date.toISOString().slice(0,10).replace(/-/g,'')}-${String(n).padStart(4,'0')}`;
export const nextPick=(rows,date=new Date())=>{const day=date.toISOString().slice(0,10).replace(/-/g,''),used=new Set((rows||[]).map(r=>r.oid).filter(x=>String(x).startsWith(`${day}-`)));let n=1;while(used.has(`${day}-${String(n).padStart(4,'0')}`))n++;return `${day}-${String(n).padStart(4,'0')}`};
export const collect=(qty,price,manual)=>manual===''||manual==null?Math.max(1,Number(qty)||1)*Math.max(0,Number(price)||0):Math.max(0,Number(manual));
export const draftCollect=d=>d?.cod!==''&&d?.cod!=null?Math.max(0,Number(d.cod)||0):d?.price===''||d?.price==null?'':collect(d.qty,d.price,'');
export const blankDraft=()=>({customerId:'',qty:1,price:'',cod:'',ship:'',salesFee:'',deliverAt:'',deliverTime:'',pay:'COD',notes:'',reference:'',scan:null});
export const blankBatchRow=(input={})=>({id:input.id||uid('batch'),image:input.image||'',fileName:input.fileName||'',selected:false,status:input.status||'queued',contact:input.contact||null,contactOpen:input.contactOpen??false,customerId:input.customerId||'',qty:input.qty??1,copies:input.copies??1,price:input.price??'',cod:input.cod??'',ship:input.ship??'',salesFee:input.salesFee??'',pay:input.pay||'COD',addedParcelIds:input.addedParcelIds||[],printed:!!input.printed,error:input.error||''});
export const batchCollect=row=>row?.cod!==''&&row?.cod!=null?Math.max(0,Number(row.cod)||0):row?.price===''||row?.price==null?'':collect(row.qty,row.price,'');
export const selectBatchRows=(rows,ids,selected=true)=>(rows||[]).map(r=>new Set(ids).has(r.id)?{...r,selected}:r);
export const deleteBatchRows=(rows,ids)=>(rows||[]).filter(r=>!new Set(ids).has(r.id));
export const applyBatchCustomer=(rows,ids,customerId)=>(rows||[]).map(r=>new Set(ids).has(r.id)?{...r,customerId,status:'ready'}:r);
export function addBatchRowsToManifest(rows,ids,customers,manifest,date=new Date()){const idSet=new Set(ids),created=[];for(const row of rows||[]){if(!idSet.has(row.id)||row.addedParcelIds?.length)continue;const customer=(customers||[]).find(c=>c.id===row.customerId);if(!customer)throw Error('Choose or confirm a customer first');if(row.price==='')throw Error('Price not found — enter it manually before adding');const parcel=createParcel({qty:row.qty,price:row.price,cod:row.cod,ship:row.ship,salesFee:row.salesFee,pay:row.pay},customer,0,date,[...(manifest||[]),...created]);created.push(parcel)}return created}
export function mergeBatchRows(rows,ids){const chosen=(rows||[]).filter(r=>new Set(ids).has(r.id)),groups=new Map();for(const r of chosen){if(!r.customerId||!r.contact?.phone)continue;const k=`${r.customerId}|${String(r.contact.phone).replace(/\D/g,'')}`;groups.set(k,[...(groups.get(k)||[]),r])}const remove=new Set(),merged=[];for(const group of groups.values()){if(group.length<2)continue;const [first,...rest]=group;const same=group.every(r=>String(r.contact.phone).replace(/\D/g,'')===String(first.contact.phone).replace(/\D/g,''));if(!same)continue;const out={...first,qty:group.reduce((n,r)=>n+Math.max(1,Number(r.qty)||1),0),copies:group.reduce((n,r)=>n+Math.max(1,Number(r.copies)||1),0),price:group.every(r=>String(r.price)===String(first.price))?first.price:'',cod:group.every(r=>r.cod===''||r.cod==null)?'':group.reduce((n,r)=>n+(Number(batchCollect(r))||0),0),ship:group.reduce((n,r)=>n+(Number(r.ship)||0),0),salesFee:group.reduce((n,r)=>n+(Number(r.salesFee)||0),0),status:'ready'};rest.forEach(r=>remove.add(r.id));merged.push(out)}return{rows:(rows||[]).filter(r=>!remove.has(r.id)).map(r=>merged.find(m=>m.id===r.id)||r),merged:merged.length}}
export function createCustomer(input={}){const phone=clean(input.phone).replace(/[\s.-]/g,'');if(!clean(input.name))throw Error('Customer name is required');if(phone&&!validPhone(phone))throw Error('Use a valid Malagasy mobile number (032–039, excluding 036)');if(clean(input.address)&&!validAddress(input.address))throw Error('Address needs an operational address indicator (Lot, Rue, Cité, etc.)');return{id:input.id||uid('customer'),name:clean(input.name),phone,area:clean(input.area),address:clean(input.address),note:clean(input.note),createdAt:input.createdAt||new Date().toISOString()}}
export const customerKey=c=>`${clean(c?.name).toLowerCase()}|${clean(c?.phone).replace(/\D/g,'')}`;
export const findDuplicate=(list,c,except=c?.id)=>(list||[]).find(x=>x.id!==except&&customerKey(x)===customerKey(c));
export const searchCustomers=(list,q)=>{q=clean(q).toLowerCase();return !q?[...(list||[])]:[...(list||[])].filter(c=>[c.name,c.phone,c.area,c.address].join(' ').toLowerCase().includes(q))};
export function upsertCustomer(list,input){const c=createCustomer(input),duplicate=findDuplicate(list,c,c.id);if(duplicate)throw Error(`Duplicate customer: ${duplicate.name}`);const i=list.findIndex(x=>x.id===c.id);i<0?list.push(c):list.splice(i,1,c);return c}
export const deleteCustomers=(list,ids)=>{const remove=new Set(ids);return(list||[]).filter(c=>!remove.has(c.id))};
export function createParcel(draft,customer,counter=0,date=new Date(),rows=[]){if(!customer)throw Error('Select a saved customer');const qty=Math.max(1,Number(draft.qty)||1),price=Math.max(0,Number(draft.price)||0),salesFee=Math.max(0,Number(draft.salesFee)||0),ship=Math.max(0,Number(draft.ship)||0),cod=collect(qty,price,draft.cod),oid=nextPick(rows,date);return normalizeParcel({id:uid('parcel'),oid,rec:{...customer},qty,price,salesFee,cod,ship,pay:draft.pay||'COD',deliverAt:draft.deliverAt||'',deliverTime:draft.deliverTime||'',notes:clean(draft.notes),reference:clean(draft.reference),addedAt:date.toISOString(),deliveryStatus:'ready',done:false,paid:false})}
export const parcelSales=p=>Math.max(0,Number(p?.qty)||1)*Math.max(0,Number(p?.price)||0)+Math.max(0,Number(p?.salesFee)||0);
export const parcelCollect=p=>Math.max(0,Number(p?.cod)||0);
export const totals=rows=>(rows||[]).reduce((x,row)=>{const r=normalizeParcel(row);x.sales+=parcelSales(r);x.delivery+=Number(r.ship)||0;x.cod+=parcelCollect(r);x.total+=parcelSales(r)+(Number(r.ship)||0);return x},{sales:0,delivery:0,cod:0,total:0});
export function transition(row,next,now=new Date(),note=''){const current=statusOf(row),allowed={ready:['in_transit','exception'],in_transit:['delivered','exception'],exception:['in_transit','delivered'],delivered:[]};if(current==='delivered'&&next!=='delivered')throw Error('Delivered parcels cannot regress');if(!allowed[current].includes(next)&&next!==current)throw Error(`Cannot change ${current} to ${next}`);if(next==='exception'&&!clean(note))throw Error('An exception note is required');return normalizeParcel({...row,deliveryStatus:next,done:next==='delivered',statusUpdatedAt:now.toISOString(),exceptionAt:next==='exception'?now.toISOString():'',exceptionNote:next==='exception'?clean(note):''})}
export const blankProfile=()=>({id:uid('profile'),name:'My delivery profile',currency:'Ar',createdAt:new Date().toISOString()});
export function deleteProfile(profiles,activeId,id){if((profiles||[]).length<2)throw Error('The final profile cannot be deleted');const target=profiles.find(p=>p.id===id);if(!target)throw Error('Profile not found');const next=profiles.filter(p=>p.id!==id);return{profiles:next,activeId:activeId===id?next[0].id:activeId,deleted:target}}
export function storage(profileId){const read=(k,d)=>{try{const v=localStorage.getItem(`lz.beta3.${profileId}.${k}`);return v?JSON.parse(v):d}catch{return d}},write=(k,v)=>localStorage.setItem(`lz.beta3.${profileId}.${k}`,JSON.stringify(v));const state={shop:read('shop',{}),addr:read('addr',[]),manifest:read('mani',[]).map(normalizeParcel),archive:read('arch',[]),counter:Number(read('ctr',0))||0,labelVault:read('labels',[]),draft:{...blankDraft(),...read('draft',{})},batch:read('batch',[])};return{state,save(){[['shop',state.shop],['addr',state.addr],['mani',state.manifest],['arch',state.archive],['ctr',state.counter],['labels',state.labelVault],['draft',state.draft],['batch',state.batch]].forEach(([k,v])=>write(k,v))}}}
