import{validPhone,validAddress,parcelCollect,parcelSales}from'./core.js';
export function contactFromText(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),all=lines.join(' '),match=all.match(/(?:\+261|0)(?:[ .-]?\d){9}/)?.[0]||'',phone=match.replace(/^\+261/,'0').replace(/[ .-]/g,''),address=lines.find(validAddress)||'',name=lines.find(x=>/^[A-Za-zÀ-ÿ' -]{3,40}$/.test(x)&&x!==address)||'';return{phone:validPhone(phone)?phone:'',address,name,text:String(text||'')}}
export async function ocrPhoto(file){if(!file)throw Error('Choose a photo first');if(!window.Tesseract)await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>bad(Error('OCR engine could not load. Check your connection and try again.'));document.head.append(s)});const result=await window.Tesseract.recognize(file,'eng+fra');return contactFromText(result.data.text)}
const escPdf=s=>String(s??'').replace(/[\\()]/g,'\\$&').replace(/[^\x20-\x7e]/g,'?');
export function labelPdfBlob(parcel,shop={}){const lines=[shop.name||'LABELONZEWAY',parcel.oid,parcel.rec?.name||'',parcel.rec?.phone||'',parcel.rec?.address||'',`QTY ${parcel.qty||1}  COLLECT ${parcelCollect(parcel)}`,`DELIVERY ${Number(parcel.ship||0)}`,parcel.reference?`REF ${parcel.reference}`:''].filter(Boolean);const stream=`BT /F1 10 Tf 10 270 Td ${lines.map((x,i)=>`${i?'0 -15 Td ':''}(${escPdf(x)}) Tj`).join(' ')} ET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 204 288] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offset=[0];objects.forEach((o,i)=>{offset.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offset.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
export async function labelPngBlob(parcel,shop={}){const canvas=document.createElement('canvas');canvas.width=576;canvas.height=820;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,576,820);c.fillStyle='#111';c.font='bold 30px monospace';c.fillText(shop.name||'LABELONZEWAY',28,54);c.font='bold 38px monospace';c.fillText(parcel.oid||'',28,115);c.strokeStyle='#111';c.setLineDash([8,6]);c.beginPath();c.moveTo(28,140);c.lineTo(548,140);c.stroke();c.setLineDash([]);c.font='25px monospace';const lines=[parcel.rec?.name,parcel.rec?.phone,parcel.rec?.address,`Qty: ${parcel.qty||1}`,`Collect: ${parcelCollect(parcel)}`,`Delivery: ${Number(parcel.ship||0)}`,parcel.reference&&`Ref: ${parcel.reference}`].filter(Boolean);lines.forEach((l,i)=>c.fillText(String(l).slice(0,34),28,190+i*48));return new Promise(ok=>canvas.toBlob(b=>ok(b),'image/png'))}
export function manifestCsv(rows){const h=['Pick ID','Customer','Address','Phone','Sales','Delivery','COD','Payment','Status'];return[h,...rows.map(r=>[r.oid,r.rec?.name,r.rec?.address,r.rec?.phone,parcelSales(r),r.ship,parcelCollect(r),r.pay,r.deliveryStatus])].map(a=>a.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
export function downloadBlob(blob,name){if(!blob||blob.size<1)throw Error('File generation failed');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);return a.href}
export async function shareFile(blob,name,title='LabelOnZeWay label'){if(!blob||blob.size<1)throw Error('File generation failed');const file=new File([blob],name,{type:blob.type});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title,files:[file]});return'Native share opened'}throw Error('Native file sharing is unavailable on this browser. Download the file instead.')}
export const whatsappLink=parcel=>`https://wa.me/?text=${encodeURIComponent(`LabelOnZeWay ${parcel.oid}: ${location.origin}${location.pathname.replace(/\/(command|guided|rider|tracking)\/?$/,'')}tracking/?pick=${encodeURIComponent(parcel.oid)}`)}`;
