const CONFIG='/FBP/labelonzeway/sync-config.json',FUNCTION='create-label-share';
let clientPromise;
async function client(){if(clientPromise)return clientPromise;clientPromise=(async()=>{const config=await fetch(CONFIG,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(Error('tracking configuration unavailable')));const lib=window.supabase||await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js';s.onload=()=>ok(window.supabase);s.onerror=()=>bad(Error('Supabase library unavailable'));document.head.append(s)});return lib.createClient(config.supabaseUrl,config.supabaseAnonKey)})();return clientPromise}
async function sessionClient(action='create a secure tracking link'){const c=await client(),{data:{session}}=await c.auth.getSession();if(!session)throw Error(`Sign in to ${action}`);return[c,session]}
async function generate(parcel){const[c]=await sessionClient();const workspace_id=localStorage.getItem('lz.cloud.workspace.v1')||'',profile_id=localStorage.getItem('lz.beta3.activeProfile')||'';if(!workspace_id||!profile_id)throw Error('Choose a shared workspace before creating a secure link');const{data,error}=await c.functions.invoke(FUNCTION,{body:{workspace_id,profile_id,parcel_id:parcel?.id,order_number:parcel?.oid,status:parcel?.deliveryStatus}});if(error)throw Error(error.message||'Secure-link backend error');if(!data?.url||!data?.expires_at||!data?.token)throw Error('Secure-link backend returned no URL or expiry; no link was copied.');return data}
const publicStatus={ready:'ready',in_transit:'in_transit',delivered:'delivered',exception:'exception'};
async function updateStatus(parcel){const[c]=await sessionClient('update tracking status'),workspace_id=localStorage.getItem('lz.cloud.workspace.v1')||'',profile_id=localStorage.getItem('lz.beta3.activeProfile')||'',status=publicStatus[parcel?.deliveryStatus];if(!workspace_id||!profile_id)throw Error('Choose a shared workspace before updating tracking');if(!parcel?.id||!parcel?.oid||!status)throw Error('Tracking sync pending: parcel status is invalid');const{error}=await c.rpc('upsert_parcel_tracking_projection',{p_workspace_id:workspace_id,p_profile_id:profile_id,p_parcel_id:parcel.id,p_order_number:parcel.oid,p_status:status});if(error){const message=String(error.message||'');if(/network|fetch/i.test(message))throw Error('Tracking sync pending: Network error. Check your connection and retry.');throw Error(`Tracking sync pending: Backend error: ${message||'unable to update public tracking'}`)}return{status}}
async function lookup(token){if(!/^[0-9a-f-]{36}$/i.test(String(token||'')))throw Error('Invalid tracking token');const c=await client(),{data,error}=await c.rpc('public_parcel_tracking',{p_token:token});if(error)throw Error(error.message||'Tracking lookup failed');const row=Array.isArray(data)?data[0]:data;if(!row||row.link_state==='not_found')return{state:'not_found'};if(row.link_state==='expired'||row.link_state==='revoked')return{state:row.link_state};return{state:'active',order_number:row.order_number,status:row.status,updated_at:row.updated_at}}
async function revoke(reference){const[c]=await sessionClient();if(!reference?.workspace_id||!reference?.profile_id||!reference?.parcel_id)throw Error('Parcel reference is required to revoke a secure link');const{error}=await c.rpc('revoke_parcel_tracking_token',{p_workspace_id:reference.workspace_id,p_profile_id:reference.profile_id,p_parcel_id:reference.parcel_id});if(error)throw Error(error.message||'Could not revoke secure link');return true}
window.LabelOnZeWayBetaTracking={generate,lookup,revoke,updateStatus};
document.addEventListener('DOMContentLoaded',async()=>{const token=new URLSearchParams(location.search).get('token');if(!token||!/\/tracking\/?$/.test(location.pathname))return;const result=document.querySelector('[data-result]');if(!result)return;try{const row=await lookup(token);if(row.state==='active')result.innerHTML=`<h3>${row.order_number}</h3><p>${row.status}</p><p>Updated ${row.updated_at}</p>`;else result.textContent=row.state==='expired'?'This tracking link has expired.':row.state==='revoked'?'This tracking link was revoked.':'Tracking link not found.'}catch(e){result.textContent=`Tracking lookup unavailable: ${e.message}`}});
