import{cp,mkdir,rm,writeFile}from'node:fs/promises';
const out='labelonzeway-beta3';
await rm(out,{recursive:true,force:true});await mkdir(`${out}/app`,{recursive:true});await mkdir(`${out}/icons`,{recursive:true});
for(const f of['app.js','core.js','operations.js','tracking-adapter.js','styles.css','print.css'])await cp(`app/${f}`,`${out}/app/${f}`);
for(const f of['icon-192.png','icon-512.png','icon-maskable-192.png','icon-maskable-512.png'])await cp(`icons/${f}`,`${out}/icons/${f}`);
const head=(prefix='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102a43"><link rel="manifest" href="${prefix}manifest.webmanifest"><link rel="stylesheet" href="${prefix}app/styles.css"><link rel="stylesheet" href="${prefix}app/print.css" media="print"><title>LabelOnZeWay Beta 3 UAT</title></head><body><script src="${prefix}app/tracking-adapter.js"></script><script type="module" src="${prefix}app/app.js"></script></body></html>`;
await writeFile(`${out}/index.html`,head());for(const route of['command','guided','rider','tracking']){await mkdir(`${out}/${route}`,{recursive:true});await writeFile(`${out}/${route}/index.html`,head('../'))}
await writeFile(`${out}/manifest.webmanifest`,JSON.stringify({id:'./',name:'LabelOnZeWay Beta 3 UAT',short_name:'LabelOnZeWay',start_url:'./',scope:'./',display:'standalone',theme_color:'#102a43',background_color:'#f5f1e9',icons:[192,512].flatMap(size=>[{src:`icons/icon-${size}.png`,sizes:`${size}x${size}`,type:'image/png'},{src:`icons/icon-maskable-${size}.png`,sizes:`${size}x${size}`,type:'image/png',purpose:'maskable'}])},null,2));
await writeFile(`${out}/service-worker.js`,"const CACHE='labelonzeway-beta3-uat-2';const BASE=new URL('./',self.location).pathname;const SHELL=['','index.html','app/app.js','app/core.js','app/operations.js','app/tracking-adapter.js','app/styles.css','app/print.css','command/','guided/','rider/','tracking/'].map(x=>BASE+x);self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==location.origin)return;e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request)))})");
