import {createHash} from 'node:crypto';
import {cp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';

const out='theta77';
const assets=['index.html','app/app.js','app/core.js','app/operations.js','app/styles.css','app/print.css','app/assets/luz-circular-thermal.png','manifest.webmanifest','icons/icon-192.png','icons/icon-512.png','icons/icon-maskable-192.png','icons/icon-maskable-512.png','command/index.html','guided/index.html','rider/index.html','manifest/index.html','tracking/index.html','settings/index.html'];
const version=entries=>{const h=createHash('sha256');for(const [path,content] of entries.sort(([a],[b])=>a.localeCompare(b)))h.update(path).update('\0').update(content).update('\0');return h.digest('hex').slice(0,16)};
const worker=v=>`const PREFIX='theta77-';const CACHE='theta77-${v}';const BASE=new URL('./',self.location).pathname;const ASSETS=${JSON.stringify(assets)}.map(x=>BASE+x);const scoped=u=>u.origin===self.location.origin&&u.pathname.startsWith(BASE);self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||!scoped(u))return;e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match(BASE+'index.html'))))});`;

export async function buildTheta77(output=out){
 await rm(output,{recursive:true,force:true}); await mkdir(`${output}/app/assets`,{recursive:true}); await mkdir(`${output}/icons`,{recursive:true});
 for(const f of ['operations.js','print.css']) await cp(`app/${f}`,`${output}/app/${f}`);
 await cp('theta77-dispatch-studio.css',`${output}/app/styles.css`);
 let core=await readFile('app/core.js','utf8'); await writeFile(`${output}/app/core.js`,core.replaceAll('lz.beta3','lz.theta77'));
 await cp('app/assets/luz-circular-thermal.png',`${output}/app/assets/luz-circular-thermal.png`);
 for(const f of ['icon-192.png','icon-512.png','icon-maskable-192.png','icon-maskable-512.png']) await cp(`icons/${f}`,`${output}/icons/${f}`);
 let app=await readFile('app/app.js','utf8');
 app=app.replaceAll('lz.beta3','lz.theta77').replaceAll('LabelOnZeWayBetaTracking','Theta77Tracking').replaceAll('LabelOnZeWay','THETA77').replaceAll('labelonzeway','theta77');
 app=app.replaceAll('(command|guided|rider|tracking)','(command|guided|rider|manifest|tracking|settings)');
 app=app.replace('({command,guided,rider,tracking}[route])();','({command,guided,rider,manifest:command,tracking,settings:command}[route])();');
 app=app.replace('<a href="${BASE}rider/" title="Rider" aria-label="Rider"><span aria-hidden="true">➜</span><span class="nav-label">Rider</span></a><a href="${BASE}tracking/"', '<a href="${BASE}rider/" title="Rider" aria-label="Rider"><span aria-hidden="true">➜</span><span class="nav-label">Rider</span></a><a href="${BASE}manifest/" title="Manifest" aria-label="Manifest"><span aria-hidden="true">☷</span><span class="nav-label">Manifest</span></a><a href="${BASE}settings/" title="Settings" aria-label="Settings"><span aria-hidden="true">⚙</span><span class="nav-label">Settings</span></a><a href="${BASE}tracking/"');
 app=app.replace("if(route==='guided')stitchGuided();", "if(route==='manifest'){command();document.querySelector('.grid-command').remove();}else if(route==='settings'){const r=root('Settings', '<section class=\"card\"><h2>Profile and printer settings</h2><p>Manage profiles, business identity, thermal logo, gateway, backups and address book.</p><button class=\"button teal\" data-open-settings>Open Profile Manager</button></section>');r.querySelector('[data-open-settings]').onclick=profileManager}else if(route==='guided')stitchGuided();");
 app=app.replace('</div><div class="actions"><button class="button ghost" data-profiles>Profiles / backup</button>', '</div><span class="dispatch-state">● Local state</span><div class="actions"><button class="button ghost" data-theme>Theme</button><button class="button ghost" data-profiles>Profiles / backup</button>');
 app=app.replace("r.querySelector('[data-profiles]').onclick=profileManager;return r}", "r.querySelector('[data-profiles]').onclick=profileManager;const theme=r.querySelector('[data-theme]');theme.onclick=()=>{const dark=document.body.dataset.theme==='dark';document.body.dataset.theme=dark?'light':'dark';localStorage.setItem('lz.theta77.theme',dark?'light':'dark')};document.body.dataset.theme=localStorage.getItem('lz.theta77.theme')||'light';return r}");
 await writeFile(`${output}/app/app.js`,app);
 const head=(prefix='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102a43"><link rel="manifest" href="${prefix}manifest.webmanifest"><link rel="stylesheet" href="${prefix}app/styles.css"><link rel="stylesheet" href="${prefix}app/print.css" media="print"><title>THETA77 Local UAT</title></head><body><script>window.Theta77Tracking={updateStatus:async parcel=>({status:parcel.deliveryStatus}),generate:async()=>{throw Error('Public secure tracking is unavailable in this isolated local UAT build. Use local Pick ID tracking.')}}</script><script type="module" src="${prefix}app/app.js"></script></body></html>`;
 await writeFile(`${output}/index.html`,head()); for(const route of ['command','guided','rider','manifest','tracking','settings']){await mkdir(`${output}/${route}`,{recursive:true});await writeFile(`${output}/${route}/index.html`,head('../'));}
 await writeFile(`${output}/manifest.webmanifest`,JSON.stringify({id:'./',name:'THETA77 Local UAT',short_name:'THETA77',start_url:'./command/',scope:'./',display:'standalone',theme_color:'#102a43',background_color:'#f5f1e9',icons:[192,512].flatMap(s=>[{src:`icons/icon-${s}.png`,sizes:`${s}x${s}`,type:'image/png'},{src:`icons/icon-maskable-${s}.png`,sizes:`${s}x${s}`,type:'image/png',purpose:'maskable'}])},null,2));
 const cache=version(await Promise.all(assets.map(async p=>[p,await readFile(`${output}/${p}`)]))); await writeFile(`${output}/service-worker.js`,worker(cache)); return cache;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)console.log(await buildTheta77());
