(()=>{
'use strict';
const K='lz.ai.uat.v1';
const seed={drafts:[],customers:[],parcels:[],archive:[],prints:[],claims:[],events:[],source:'whatsapp',lastWrite:null};
const load=()=>{try{return Object.assign({},seed,JSON.parse(localStorage.getItem(K)||'{}'))}catch{return structuredClone(seed)}};
let s=load(),editingCustomer=null;
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'Ar '+Number(n||0).toLocaleString('fr-FR');
function persist(){s.lastWrite=new Date().toISOString();localStorage.setItem(K,JSON.stringify(s));renderAll()}
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function id(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)}
function pick(){const d=new Date(), key=`${d.getDate()}${d.getMonth()+1}${String(d.getFullYear()).slice(-2)}`;const n=s.parcels.filter(p=>p.pick?.startsWith(key+'-')).length+s.archive.filter(p=>p.pick?.startsWith(key+'-')).length+1;return `${key}-${n}`}
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
$$('[data-source]').forEach(b=>b.addEventListener('click',()=>{$$('[data-source]').forEach(x=>x.classList.remove('active'));b.classList.add('active');s.source=b.dataset.source;persist()}));
function normalizePhone(text){const m=String(text).match(/(?:\+?261\s*)?(0?3[2345789])(?:[\s.-]*\d){7}/);if(!m)return'';let x=m[0].replace(/\D/g,'');if(x.startsWith('261'))x='0'+x.slice(3);if(!x.startsWith('0'))x='0'+x;return x.slice(0,10)}
function parseMessage(text){const raw=String(text||'').trim(), low=raw.toLowerCase();let score=20;const phone=normalizePhone(raw);if(phone)score+=18;
 const qtym=raw.match(/(?:qty|quantit[eé]|alefaso|envoyer|send|x)\s*[:=-]?\s*(\d{1,3})|\b(\d{1,3})\s*(?:pcs|pi[eè]ces?|articles?|robes?|items?)/i);const qty=Number(qtym?.[1]||qtym?.[2]||1);if(qtym)score+=10;
 const amounts=[...raw.matchAll(/(\d[\d\s.,]{2,})\s*(?:ar|ariary)/ig)].map(m=>Number(m[1].replace(/\D/g,''))).filter(Boolean);const cod=amounts.length?Math.max(...amounts):0;if(cod)score+=15;
 let lang=/\b(salama|alefaso|misaotra|azafady|akaiky|eny)\b/i.test(raw)?'Malagasy':(/\b(livraison|demain|bonjour|près|adresse|merci)\b/i.test(raw)?'French':'English');
 const nameM=raw.match(/(?:name|nom|client)\s*[:=-]\s*([A-Za-zÀ-ÿ' -]{3,45})/i);let name=nameM?nameM[1].trim():'';if(name)score+=8;
 const landmarks=['shoprite','jumbo','score','station','église','eglise','école','ecole','pharmacie','banque','arrêt','arret','mosquée','mosquee'];let landmark='';for(const w of landmarks){const i=low.indexOf(w);if(i>=0){landmark=raw.slice(i,Math.min(raw.length,i+55)).split(/[,.\n]/)[0].trim();break}}if(landmark)score+=7;
 const areaList=['analakely','anosy','ivandry','ankorondrano','ambohijatovo','isotry','67 ha','tanjombato','ambohipo','andraharo','antanimena','behoririka','ampefiloha','ambanidia','mahamasina','talatamaty'];let area='';for(const a of areaList){if(low.includes(a)){area=a.replace(/\b\w/g,c=>c.toUpperCase());break}}if(area)score+=12;
 let date='';const d=new Date();if(/demain|rahampitso|tomorrow/i.test(raw)){d.setDate(d.getDate()+1);date=d.toISOString().slice(0,10);score+=5}else{const dm=raw.match(/\b(\d{1,2})[\/-](\d{1,2})(?:[\/-](\d{2,4}))?\b/);if(dm){const y=dm[3]?Number(dm[3].length===2?'20'+dm[3]:dm[3]):new Date().getFullYear();date=`${y}-${String(dm[2]).padStart(2,'0')}-${String(dm[1]).padStart(2,'0')}`;score+=5}}
 let items='';const im=raw.match(/(?:alefaso|send|envoyer|commande|order)\s+(?:moi\s+)?(?:\d+\s+)?([^,.\n]{3,60})/i);if(im)items=im[1].replace(/\b(?:total|livraison|delivery)\b.*$/i,'').trim();if(items)score+=5;
 const missing=[];if(!phone)missing.push('phone');if(!area)missing.push('address/area');if(!cod)missing.push('COD amount');if(!items)missing.push('items');score=Math.max(5,Math.min(score,97));
 return {raw,source:s.source,name,phone,address:area,landmark,qty,cod,date,lang,items,notes:'',confidence:score,missing};
}
function fillDraft(d){$('fName').value=d.name||'';$('fPhone').value=d.phone||'';$('fAddress').value=d.address||'';$('fLandmark').value=d.landmark||'';$('fQty').value=d.qty||1;$('fCod').value=d.cod||'';$('fDate').value=d.date||'';$('fLang').value=d.lang||'';$('fItems').value=d.items||'';$('fNotes').value=d.notes||'';$('confidence').textContent=`${d.confidence||0}% confidence`;const m=d.missing||[];$('missing').classList.toggle('hidden',!m.length);$('missing').textContent=m.length?'Needs review: '+m.join(', '):'';$('draftForm').dataset.raw=d.raw||'';$('draftForm').dataset.source=d.source||s.source;$('draftForm').dataset.confidence=d.confidence||0}
function formDraft(){const d={id:id('draft'),raw:$('draftForm').dataset.raw||$('messageInput').value,source:$('draftForm').dataset.source||s.source,name:$('fName').value.trim(),phone:$('fPhone').value.trim(),address:$('fAddress').value.trim(),landmark:$('fLandmark').value.trim(),qty:Math.max(1,Number($('fQty').value||1)),cod:Number(String($('fCod').value).replace(/\D/g,'')),date:$('fDate').value,lang:$('fLang').value.trim(),items:$('fItems').value.trim(),notes:$('fNotes').value.trim(),confidence:Number($('draftForm').dataset.confidence||0),status:'needs_review',createdAt:new Date().toISOString()};d.missing=[];if(!d.phone)d.missing.push('phone');if(!d.address)d.missing.push('address');if(!d.cod)d.missing.push('COD');if(!d.items)d.missing.push('items');return d}
$('analyzeBtn').addEventListener('click',()=>{const d=parseMessage($('messageInput').value);if(!d.raw)return toast('Enter a customer message first');fillDraft(d);toast('Draft extracted — review before confirmation')});
$('sampleBtn').addEventListener('click',()=>{$('messageInput').value='Salama, alefaso 2 robe noire, 80 000 Ar total. Livraison Analakely près de Shoprite rahampitso. Tel 0341234567';$('analyzeBtn').click()});
$('saveDraftBtn').addEventListener('click',e=>{e.preventDefault();const d=formDraft();s.drafts.unshift(d);persist();toast('Needs-review draft saved')});
$('confirmBtn').addEventListener('click',e=>{e.preventDefault();const d=formDraft();if(d.missing.length)return toast('Complete required fields before creating shipment');let c=s.customers.find(x=>x.phone===d.phone);if(!c){c={id:id('cust'),name:d.name||'Customer '+d.phone.slice(-4),phone:d.phone,address:d.address,landmark:d.landmark};s.customers.unshift(c)}else{c.name=d.name||c.name;c.address=d.address||c.address;c.landmark=d.landmark||c.landmark}
 const p={id:id('parcel'),pick:pick(),customerId:c.id,name:c.name,phone:c.phone,address:d.address,landmark:d.landmark,qty:d.qty,cod:d.cod,items:d.items,notes:d.notes,deliveryDate:d.date,status:'ready',selected:false,source:d.source,evidence:d.raw,confidence:d.confidence,createdAt:new Date().toISOString()};s.parcels.unshift(p);s.claims.unshift({id:id('claim'),pick:p.pick,type:'label-record',createdAt:p.createdAt,identity:{name:p.name,phone:p.phone,address:p.address},immutable:true});s.events.unshift({id:id('evt'),pick:p.pick,status:'ready',at:p.createdAt,source:'confirmed AI draft'});s.prints.unshift({id:id('print'),pick:p.pick,state:'queued',at:p.createdAt,copies:1});persist();$('messageInput').value='';fillDraft({});showView('manifest');toast(`${p.pick} confirmed and added to manifest`)});
$('clearDrafts').addEventListener('click',()=>{s.drafts=s.drafts.filter(d=>d.status==='needs_review');persist();toast('Resolved drafts cleared')});
function renderDrafts(){const el=$('draftList');el.innerHTML=s.drafts.length?s.drafts.map(d=>`<div class="listItem"><div><b>${esc(d.name||d.phone||'Unidentified customer')}</b><div class="meta">${esc(d.source)} · ${esc(d.items||'No item')} · ${money(d.cod)} · ${d.confidence}%</div></div><div class="row"><button data-load-draft="${d.id}">Review</button><button data-delete-draft="${d.id}">Delete</button></div></div>`).join(''):'<div class="meta">No saved drafts.</div>'}
document.addEventListener('click',e=>{const ld=e.target.closest('[data-load-draft]');if(ld){const d=s.drafts.find(x=>x.id===ld.dataset.loadDraft);if(d){$('messageInput').value=d.raw||'';fillDraft(d);showView('intake')}}const dd=e.target.closest('[data-delete-draft]');if(dd){s.drafts=s.drafts.filter(x=>x.id!==dd.dataset.deleteDraft);persist()}});
function openCustomer(c){editingCustomer=c?.id||null;$('modalTitle').textContent=c?'Edit customer':'New customer';$('cName').value=c?.name||'';$('cPhone').value=c?.phone||'';$('cAddress').value=c?.address||'';$('cLandmark').value=c?.landmark||'';$('modal').classList.remove('hidden');$('cName').focus()}
$('newCustomerBtn').addEventListener('click',()=>openCustomer());$('modalClose').addEventListener('click',()=>{$('modal').classList.add('hidden')});$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')});
$('customerForm').addEventListener('submit',e=>{e.preventDefault();const v={name:$('cName').value.trim(),phone:normalizePhone($('cPhone').value)||$('cPhone').value.trim(),address:$('cAddress').value.trim(),landmark:$('cLandmark').value.trim()};if(!v.name||!v.phone)return toast('Name and phone are required');const dup=s.customers.find(x=>x.phone===v.phone&&x.id!==editingCustomer);if(dup)return toast('That phone already exists');if(editingCustomer)Object.assign(s.customers.find(x=>x.id===editingCustomer),v);else s.customers.unshift({id:id('cust'),...v});$('modal').classList.add('hidden');persist();toast('Customer saved')});
$('customerSearch').addEventListener('input',renderCustomers);
function renderCustomers(){const q=$('customerSearch').value.toLowerCase();const a=s.customers.filter(c=>[c.name,c.phone,c.address,c.landmark].join(' ').toLowerCase().includes(q));$('customerList').innerHTML=a.length?a.map(c=>`<div class="listItem"><div><b>${esc(c.name)}</b><div class="meta">${esc(c.phone)} · ${esc(c.address)} ${esc(c.landmark)}</div></div><div class="row"><button data-edit-customer="${c.id}">Edit</button><button data-use-customer="${c.id}">Create label</button></div></div>`).join(''):'<div class="meta">No matching customers.</div>'}
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit-customer]');if(ed)openCustomer(s.customers.find(x=>x.id===ed.dataset.editCustomer));const use=e.target.closest('[data-use-customer]');if(use){const c=s.customers.find(x=>x.id===use.dataset.useCustomer);if(c){fillDraft({name:c.name,phone:c.phone,address:c.address,landmark:c.landmark,qty:1,confidence:100,missing:['COD amount','items'],source:'address-book'});showView('intake')}}});
function renderManifest(){const el=$('manifestList');el.innerHTML=s.parcels.length?s.parcels.map(p=>`<div class="manifestRow"><input type="checkbox" aria-label="Select ${esc(p.pick)}" data-select="${p.id}" ${p.selected?'checked':''}><div><b>${esc(p.pick)}</b><div class="meta">${esc(p.name)}</div></div><div class="mobileHide">${esc(p.address)} ${esc(p.landmark)}</div><div class="hideTablet">${money(p.cod)}</div><div class="mobileHide hideTablet">Qty ${p.qty}</div><div><span class="status ${p.status}">${esc(p.status)}</span></div><div class="row"><button data-status-one="${p.id}">Status</button><button data-track="${p.pick}">Track</button></div></div>`).join(''):'<div class="manifestRow"><div></div><div class="meta">Manifest empty.</div></div>'}
document.addEventListener('change',e=>{if(e.target.matches('[data-select]')){const p=s.parcels.find(x=>x.id===e.target.dataset.select);if(p){p.selected=e.target.checked;persist()}}});
document.addEventListener('click',e=>{const st=e.target.closest('[data-status-one]');if(st){const p=s.parcels.find(x=>x.id===st.dataset.statusOne);if(!p)return;const cycle={ready:'transit',transit:'delivered',delivered:'ready',exception:'ready'};p.status=cycle[p.status]||'ready';s.events.unshift({id:id('evt'),pick:p.pick,status:p.status,at:new Date().toISOString(),source:'operator'});persist();toast(`${p.pick}: ${p.status}`)}const tr=e.target.closest('[data-track]');if(tr){$('trackingSearch').value=tr.dataset.track;renderTracking();showView('tracking')}});
$('bulkApply').addEventListener('click',()=>{const status=$('bulkStatus').value, selected=s.parcels.filter(p=>p.selected);if(!status||!selected.length)return toast('Select parcels and a status');if(status==='exception'){selected.forEach(p=>{p.status='exception';p.exception={reason:'Operator review required',owner:'Unassigned',retryDate:''}})}else selected.forEach(p=>p.status=status);selected.forEach(p=>s.events.unshift({id:id('evt'),pick:p.pick,status:p.status,at:new Date().toISOString(),source:'bulk'}));persist();toast(`${selected.length} parcel(s) updated`)});
$('archiveSelected').addEventListener('click',()=>{const selected=s.parcels.filter(p=>p.selected);if(!selected.length)return toast('Select parcels to archive');selected.forEach(p=>s.archive.unshift({...p,selected:false,archivedAt:new Date().toISOString()}));s.parcels=s.parcels.filter(p=>!p.selected);persist();toast(`${selected.length} parcel(s) archived — Close Day not triggered`)});
function renderPrint(){const el=$('printList');el.innerHTML=s.prints.length?s.prints.map(j=>`<div class="listItem"><div><b>${esc(j.pick)}</b><div class="meta">${esc(j.state)} · ${new Date(j.at).toLocaleString()}</div></div><div class="row">${j.state==='queued'?`<button data-print-send="${j.id}">Mark sent</button><button data-print-cancel="${j.id}">Cancel</button>`:`<button data-reprint="${j.id}">Reprint</button>`}</div></div>`).join(''):'<div class="meta">Print queue empty.</div>'}
$('testPrint').addEventListener('click',()=>{s.prints.unshift({id:id('print'),pick:'TEST-'+Date.now().toString().slice(-5),state:'queued',at:new Date().toISOString(),copies:1});persist();toast('Test label queued')});
document.addEventListener('click',e=>{const send=e.target.closest('[data-print-send]');if(send){const j=s.prints.find(x=>x.id===send.dataset.printSend);j.state='sent';persist();toast('Print job marked sent')}const can=e.target.closest('[data-print-cancel]');if(can){const j=s.prints.find(x=>x.id===can.dataset.printCancel);j.state='cancelled';persist()}const re=e.target.closest('[data-reprint]');if(re){const j=s.prints.find(x=>x.id===re.dataset.reprint);s.prints.unshift({...j,id:id('print'),state:'queued',at:new Date().toISOString()});persist();toast('Explicit reprint queued')}});
function renderExceptions(){const a=s.parcels.filter(p=>p.status==='exception');$('exceptionList').innerHTML=a.length?a.map(p=>`<div class="listItem"><div><b>${esc(p.pick)} · ${esc(p.name)}</b><div class="meta">${esc(p.exception?.reason||'Reason required')} · Owner: ${esc(p.exception?.owner||'Unassigned')}</div></div><button data-resolve="${p.id}">Return to Ready</button></div>`).join(''):'<div class="meta">No active exceptions.</div>'}
document.addEventListener('click',e=>{const r=e.target.closest('[data-resolve]');if(r){const p=s.parcels.find(x=>x.id===r.dataset.resolve);p.status='ready';s.events.unshift({id:id('evt'),pick:p.pick,status:'ready',at:new Date().toISOString(),source:'exception resolved'});persist()}});
function renderClaims(){$('claimsList').innerHTML=s.claims.length?s.claims.map(c=>`<div class="listItem"><div><b>${esc(c.pick)}</b><div class="meta">Permanent electronic label record · ${new Date(c.createdAt).toLocaleString()}</div></div><span class="badge">immutable</span></div>`).join(''):'<div class="meta">No claim records yet.</div>'}
$('trackingSearch').addEventListener('input',renderTracking);function renderTracking(){const q=$('trackingSearch').value.trim().toLowerCase(),p=[...s.parcels,...s.archive].find(x=>x.pick.toLowerCase()===q);if(!q){$('trackingResult').innerHTML='';return}$('trackingResult').innerHTML=p?`<div class="card" style="margin-top:12px"><h2>${esc(p.pick)}</h2><p><span class="status ${p.status}">${esc(p.status)}</span></p><div class="meta">Public view intentionally excludes phone, full address, payment and private notes.</div><div class="stack" style="margin-top:12px">${s.events.filter(e=>e.pick===p.pick).sort((a,b)=>a.at.localeCompare(b.at)).map(e=>`<div>${new Date(e.at).toLocaleString()} · <b>${esc(e.status)}</b></div>`).join('')}</div></div>`:'<div class="warning">Tracking ID not found.</div>'}
function renderHome(){const drafts=s.drafts.filter(d=>d.status==='needs_review').length,ready=s.parcels.filter(p=>p.status==='ready').length,transit=s.parcels.filter(p=>p.status==='transit').length,ex=s.parcels.filter(p=>p.status==='exception').length,cod=s.parcels.filter(p=>p.status!=='delivered').reduce((a,p)=>a+p.cod,0);$('mDrafts').textContent=drafts;$('mReady').textContent=ready;$('mTransit').textContent=transit;$('mExceptions').textContent=ex;$('mCod').textContent=money(cod);$('draftHealth').textContent=`${drafts} drafts`;$('nextActions').innerHTML=[drafts?`${drafts} order draft(s) need review`:null,ex?`${ex} exception(s) need action`:null,s.prints.some(x=>x.state==='queued')?'Print queue has pending jobs':null,(!drafts&&!ex&&!s.prints.some(x=>x.state==='queued'))?'No urgent operational action':null].filter(Boolean).map(x=>`<div class="listItem"><span>${esc(x)}</span></div>`).join('')}
function renderSettings(){try{const bytes=new Blob([localStorage.getItem(K)||'']).size;$('storageStat').textContent=`${bytes.toLocaleString()} bytes · OK`}catch{$('storageStat').textContent='Available'}$('lastWrite').textContent=s.lastWrite?new Date(s.lastWrite).toLocaleString():'—'}
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='labelonzeway-ai-uat.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('UAT data exported')});
function renderAll(){renderHome();renderDrafts();renderCustomers();renderManifest();renderPrint();renderExceptions();renderClaims();renderTracking();renderSettings()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')$('modal').classList.add('hidden')});
window.addEventListener('error',e=>{console.error(e.error||e.message);$('syncHealth').textContent='UI error';$('syncHealth').style.color='var(--red)'});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
renderAll();
})();